codecov:
  require_ci_to_pass: true

ignore:
  - '**/*.gen.go'
  - 'v11/cmd/**/*'
  - 'v11/server/init_event_type_map.go'

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false

coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 1%
    patch:
      default:
        target: 95%
        threshold: 1%
