ignore:
  - '**/*.gen.go'
  - 'v11/cmd/**/*'

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
