// Code generated by event-bindings-gen. DO NOT EDIT.
// Source: cmd/event-bindings-gen/config.yaml

package server

import (
	"context"

	"github.com/q1bksuu/onebot-go-sdk/v11/entity"
)

type MessageEventService interface {
	HandlePrivateMessage(ctx context.Context, ev *entity.PrivateMessageEvent) (map[string]any, error)
	HandleGroupMessage(ctx context.Context, ev *entity.GroupMessageEvent) (map[string]any, error)
}

type NoticeEventService interface {
	HandleGroupFileUpload(ctx context.Context, ev *entity.GroupFileUploadEvent) (map[string]any, error)
	HandleGroupAdminSet(ctx context.Context, ev *entity.GroupAdminChangeEvent) (map[string]any, error)
	HandleGroupAdminUnset(ctx context.Context, ev *entity.GroupAdminChangeEvent) (map[string]any, error)
	HandleGroupMemberDecreaseLeave(ctx context.Context, ev *entity.GroupMemberDecreaseEvent) (map[string]any, error)
	HandleGroupMemberDecreaseKick(ctx context.Context, ev *entity.GroupMemberDecreaseEvent) (map[string]any, error)
	HandleGroupMemberDecreaseKickMe(ctx context.Context, ev *entity.GroupMemberDecreaseEvent) (map[string]any, error)
	HandleGroupMemberIncreaseApprove(ctx context.Context, ev *entity.GroupMemberIncreaseEvent) (map[string]any, error)
	HandleGroupMemberIncreaseInvite(ctx context.Context, ev *entity.GroupMemberIncreaseEvent) (map[string]any, error)
	HandleGroupBan(ctx context.Context, ev *entity.GroupBanEvent) (map[string]any, error)
	HandleFriendAdd(ctx context.Context, ev *entity.FriendAddEvent) (map[string]any, error)
	HandleGroupRecall(ctx context.Context, ev *entity.GroupRecallEvent) (map[string]any, error)
	HandleFriendRecall(ctx context.Context, ev *entity.FriendRecallEvent) (map[string]any, error)
	HandleGroupPoke(ctx context.Context, ev *entity.GroupPokeEvent) (map[string]any, error)
	HandleGroupLuckyKing(ctx context.Context, ev *entity.GroupLuckyKingEvent) (map[string]any, error)
	HandleGroupHonorChange(ctx context.Context, ev *entity.GroupHonorChangeEvent) (map[string]any, error)
}

type RequestEventService interface {
	HandleFriendRequest(ctx context.Context, ev *entity.FriendRequestEvent) (map[string]any, error)
	HandleGroupRequestAdd(ctx context.Context, ev *entity.GroupRequestEvent) (map[string]any, error)
	HandleGroupRequestInvite(ctx context.Context, ev *entity.GroupRequestEvent) (map[string]any, error)
}

type MetaEventService interface {
	HandleLifecycle(ctx context.Context, ev *entity.LifecycleEvent) (map[string]any, error)
	HandleHeartbeat(ctx context.Context, ev *entity.HeartbeatEvent) (map[string]any, error)
}

type OneBotEventService interface {
	MessageEventService
	NoticeEventService
	RequestEventService
	MetaEventService
}

func RegisterGeneratedEvents(d *EventDispatcher, svc OneBotEventService) {
	d.Register("message/private", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandlePrivateMessage(ctx, ev.(*entity.PrivateMessageEvent))
	})
	d.Register("message/group", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleGroupMessage(ctx, ev.(*entity.GroupMessageEvent))
	})
	d.Register("notice/group_upload", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleGroupFileUpload(ctx, ev.(*entity.GroupFileUploadEvent))
	})
	d.Register("notice/group_admin/set", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleGroupAdminSet(ctx, ev.(*entity.GroupAdminChangeEvent))
	})
	d.Register("notice/group_admin/unset", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleGroupAdminUnset(ctx, ev.(*entity.GroupAdminChangeEvent))
	})
	d.Register("notice/group_decrease/leave", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleGroupMemberDecreaseLeave(ctx, ev.(*entity.GroupMemberDecreaseEvent))
	})
	d.Register("notice/group_decrease/kick", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleGroupMemberDecreaseKick(ctx, ev.(*entity.GroupMemberDecreaseEvent))
	})
	d.Register("notice/group_decrease/kick_me", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleGroupMemberDecreaseKickMe(ctx, ev.(*entity.GroupMemberDecreaseEvent))
	})
	d.Register("notice/group_increase/approve", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleGroupMemberIncreaseApprove(ctx, ev.(*entity.GroupMemberIncreaseEvent))
	})
	d.Register("notice/group_increase/invite", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleGroupMemberIncreaseInvite(ctx, ev.(*entity.GroupMemberIncreaseEvent))
	})
	d.Register("notice/group_ban", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleGroupBan(ctx, ev.(*entity.GroupBanEvent))
	})
	d.Register("notice/friend_add", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleFriendAdd(ctx, ev.(*entity.FriendAddEvent))
	})
	d.Register("notice/group_recall", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleGroupRecall(ctx, ev.(*entity.GroupRecallEvent))
	})
	d.Register("notice/friend_recall", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleFriendRecall(ctx, ev.(*entity.FriendRecallEvent))
	})
	d.Register("notice/notify/poke", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleGroupPoke(ctx, ev.(*entity.GroupPokeEvent))
	})
	d.Register("notice/notify/lucky_king", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleGroupLuckyKing(ctx, ev.(*entity.GroupLuckyKingEvent))
	})
	d.Register("notice/notify/honor", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleGroupHonorChange(ctx, ev.(*entity.GroupHonorChangeEvent))
	})
	d.Register("request/friend", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleFriendRequest(ctx, ev.(*entity.FriendRequestEvent))
	})
	d.Register("request/group/add", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleGroupRequestAdd(ctx, ev.(*entity.GroupRequestEvent))
	})
	d.Register("request/group/invite", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleGroupRequestInvite(ctx, ev.(*entity.GroupRequestEvent))
	})
	d.Register("meta_event/lifecycle", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleLifecycle(ctx, ev.(*entity.LifecycleEvent))
	})
	d.Register("meta_event/heartbeat", func(ctx context.Context, ev entity.Event) (map[string]any, error) {
		return svc.HandleHeartbeat(ctx, ev.(*entity.HeartbeatEvent))
	})
}

type UnimplementedOneBotEventService struct {
	UnimplementedMessageEventService
	UnimplementedNoticeEventService
	UnimplementedRequestEventService
	UnimplementedMetaEventService
}

type UnimplementedMessageEventService struct{}

func (*UnimplementedMessageEventService) HandlePrivateMessage(ctx context.Context, ev *entity.PrivateMessageEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedMessageEventService) HandleGroupMessage(ctx context.Context, ev *entity.GroupMessageEvent) (map[string]any, error) {
	panic("unimplemented")
}

type UnimplementedNoticeEventService struct{}

func (*UnimplementedNoticeEventService) HandleGroupFileUpload(ctx context.Context, ev *entity.GroupFileUploadEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedNoticeEventService) HandleGroupAdminSet(ctx context.Context, ev *entity.GroupAdminChangeEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedNoticeEventService) HandleGroupAdminUnset(ctx context.Context, ev *entity.GroupAdminChangeEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedNoticeEventService) HandleGroupMemberDecreaseLeave(ctx context.Context, ev *entity.GroupMemberDecreaseEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedNoticeEventService) HandleGroupMemberDecreaseKick(ctx context.Context, ev *entity.GroupMemberDecreaseEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedNoticeEventService) HandleGroupMemberDecreaseKickMe(ctx context.Context, ev *entity.GroupMemberDecreaseEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedNoticeEventService) HandleGroupMemberIncreaseApprove(ctx context.Context, ev *entity.GroupMemberIncreaseEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedNoticeEventService) HandleGroupMemberIncreaseInvite(ctx context.Context, ev *entity.GroupMemberIncreaseEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedNoticeEventService) HandleGroupBan(ctx context.Context, ev *entity.GroupBanEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedNoticeEventService) HandleFriendAdd(ctx context.Context, ev *entity.FriendAddEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedNoticeEventService) HandleGroupRecall(ctx context.Context, ev *entity.GroupRecallEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedNoticeEventService) HandleFriendRecall(ctx context.Context, ev *entity.FriendRecallEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedNoticeEventService) HandleGroupPoke(ctx context.Context, ev *entity.GroupPokeEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedNoticeEventService) HandleGroupLuckyKing(ctx context.Context, ev *entity.GroupLuckyKingEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedNoticeEventService) HandleGroupHonorChange(ctx context.Context, ev *entity.GroupHonorChangeEvent) (map[string]any, error) {
	panic("unimplemented")
}

type UnimplementedRequestEventService struct{}

func (*UnimplementedRequestEventService) HandleFriendRequest(ctx context.Context, ev *entity.FriendRequestEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedRequestEventService) HandleGroupRequestAdd(ctx context.Context, ev *entity.GroupRequestEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedRequestEventService) HandleGroupRequestInvite(ctx context.Context, ev *entity.GroupRequestEvent) (map[string]any, error) {
	panic("unimplemented")
}

type UnimplementedMetaEventService struct{}

func (*UnimplementedMetaEventService) HandleLifecycle(ctx context.Context, ev *entity.LifecycleEvent) (map[string]any, error) {
	panic("unimplemented")
}
func (*UnimplementedMetaEventService) HandleHeartbeat(ctx context.Context, ev *entity.HeartbeatEvent) (map[string]any, error) {
	panic("unimplemented")
}
