// Code generated by bindings-gen. DO NOT EDIT.
// Source: cmd/bindings-gen/config.yaml

package server

import (
	"context"

	"github.com/q1bksuu/onebot-go-sdk/v11/dispatcher"
	"github.com/q1bksuu/onebot-go-sdk/v11/entity"
)

// MessageService 消息服务
type MessageService interface {
	// SendPrivateMsg 发送私聊消息.
	SendPrivateMsg(ctx context.Context, req *entity.SendPrivateMsgRequest) (*entity.ActionResponse[entity.SendPrivateMsgResponse], error)
	// SendGroupMsg 发送群消息.
	SendGroupMsg(ctx context.Context, req *entity.SendGroupMsgRequest) (*entity.ActionResponse[entity.SendGroupMsgResponse], error)
	// SendMsg 发送消息.
	SendMsg(ctx context.Context, req *entity.SendMsgRequest) (*entity.ActionResponse[entity.SendMsgResponse], error)
	// DeleteMsg 撤回消息.
	DeleteMsg(ctx context.Context, req *entity.DeleteMsgRequest) (*entity.ActionResponse[entity.DeleteMsgResponse], error)
	// GetMsg 获取消息.
	GetMsg(ctx context.Context, req *entity.GetMsgRequest) (*entity.ActionResponse[entity.GetMsgResponse], error)
	// GetForwardMsg 获取合并转发消息.
	GetForwardMsg(ctx context.Context, req *entity.GetForwardMsgRequest) (*entity.ActionResponse[entity.GetForwardMsgResponse], error)
}

// FriendService 好友与陌生人管理
type FriendService interface {
	// SendLike 发送好友赞.
	SendLike(ctx context.Context, req *entity.SendLikeRequest) (*entity.ActionResponse[entity.SendLikeResponse], error)
	// SetFriendAddRequest 处理加好友请求.
	SetFriendAddRequest(ctx context.Context, req *entity.SetFriendAddRequestRequest) (*entity.ActionResponse[entity.SetFriendAddRequestResponse], error)
	// GetStrangerInfo 获取陌生人信息.
	GetStrangerInfo(ctx context.Context, req *entity.GetStrangerInfoRequest) (*entity.ActionResponse[entity.GetStrangerInfoResponse], error)
	// GetFriendList 获取好友列表.
	GetFriendList(ctx context.Context, req *entity.GetFriendListRequest) (*entity.ActionResponse[entity.GetFriendListResponse], error)
}

// GroupAdminService 群管理
type GroupAdminService interface {
	// SetGroupKick 群组踢人.
	SetGroupKick(ctx context.Context, req *entity.SetGroupKickRequest) (*entity.ActionResponse[entity.SetGroupKickResponse], error)
	// SetGroupBan 群组单人禁言.
	SetGroupBan(ctx context.Context, req *entity.SetGroupBanRequest) (*entity.ActionResponse[entity.SetGroupBanResponse], error)
	// SetGroupAnonymousBan 群组匿名用户禁言.
	SetGroupAnonymousBan(ctx context.Context, req *entity.SetGroupAnonymousBanRequest) (*entity.ActionResponse[entity.SetGroupAnonymousBanResponse], error)
	// SetGroupWholeBan 群组全员禁言.
	SetGroupWholeBan(ctx context.Context, req *entity.SetGroupWholeBanRequest) (*entity.ActionResponse[entity.SetGroupWholeBanResponse], error)
	// SetGroupAdmin 群组设置管理员.
	SetGroupAdmin(ctx context.Context, req *entity.SetGroupAdminRequest) (*entity.ActionResponse[entity.SetGroupAdminResponse], error)
	// SetGroupAnonymous 群组匿名开关.
	SetGroupAnonymous(ctx context.Context, req *entity.SetGroupAnonymousRequest) (*entity.ActionResponse[entity.SetGroupAnonymousResponse], error)
	// SetGroupCard 设置群名片.
	SetGroupCard(ctx context.Context, req *entity.SetGroupCardRequest) (*entity.ActionResponse[entity.SetGroupCardResponse], error)
	// SetGroupName 设置群名.
	SetGroupName(ctx context.Context, req *entity.SetGroupNameRequest) (*entity.ActionResponse[entity.SetGroupNameResponse], error)
	// SetGroupLeave 退出群组.
	SetGroupLeave(ctx context.Context, req *entity.SetGroupLeaveRequest) (*entity.ActionResponse[entity.SetGroupLeaveResponse], error)
	// SetGroupSpecialTitle 设置群组专属头衔.
	SetGroupSpecialTitle(ctx context.Context, req *entity.SetGroupSpecialTitleRequest) (*entity.ActionResponse[entity.SetGroupSpecialTitleResponse], error)
	// SetGroupAddRequest 处理加群请求.
	SetGroupAddRequest(ctx context.Context, req *entity.SetGroupAddRequestRequest) (*entity.ActionResponse[entity.SetGroupAddRequestResponse], error)
}

// GroupInfoService 群信息查询
type GroupInfoService interface {
	// GetGroupInfo 获取群信息.
	GetGroupInfo(ctx context.Context, req *entity.GetGroupInfoRequest) (*entity.ActionResponse[entity.GetGroupInfoResponse], error)
	// GetGroupList 获取群列表.
	GetGroupList(ctx context.Context, req *entity.GetGroupListRequest) (*entity.ActionResponse[entity.GetGroupListResponse], error)
	// GetGroupMemberInfo 获取群成员信息.
	GetGroupMemberInfo(ctx context.Context, req *entity.GetGroupMemberInfoRequest) (*entity.ActionResponse[entity.GetGroupMemberInfoResponse], error)
	// GetGroupMemberList 获取群成员列表.
	GetGroupMemberList(ctx context.Context, req *entity.GetGroupMemberListRequest) (*entity.ActionResponse[entity.GetGroupMemberListResponse], error)
	// GetGroupHonorInfo 获取群荣誉信息.
	GetGroupHonorInfo(ctx context.Context, req *entity.GetGroupHonorInfoRequest) (*entity.ActionResponse[entity.GetGroupHonorInfoResponse], error)
}

// AccountService 账号凭证
type AccountService interface {
	// GetLoginInfo 获取登录号信息.
	GetLoginInfo(ctx context.Context, req *entity.GetLoginInfoRequest) (*entity.ActionResponse[entity.GetLoginInfoResponse], error)
	// GetCookies 获取 cookies.
	GetCookies(ctx context.Context, req *entity.GetCookiesRequest) (*entity.ActionResponse[entity.GetCookiesResponse], error)
	// GetCsrfToken 获取 csrf token.
	GetCsrfToken(ctx context.Context, req *entity.GetCsrfTokenRequest) (*entity.ActionResponse[entity.GetCsrfTokenResponse], error)
	// GetCredentials 获取登录凭证.
	GetCredentials(ctx context.Context, req *entity.GetCredentialsRequest) (*entity.ActionResponse[entity.GetCredentialsResponse], error)
}

// MediaService 媒体获取
type MediaService interface {
	// GetRecord 获取语音.
	GetRecord(ctx context.Context, req *entity.GetRecordRequest) (*entity.ActionResponse[entity.GetRecordResponse], error)
	// GetImage 获取图片.
	GetImage(ctx context.Context, req *entity.GetImageRequest) (*entity.ActionResponse[entity.GetImageResponse], error)
}

// CapabilityService 能力检查
type CapabilityService interface {
	// CanSendImage 检查是否可以发送图片.
	CanSendImage(ctx context.Context, req *entity.CanSendImageRequest) (*entity.ActionResponse[entity.CanSendImageResponse], error)
	// CanSendRecord 检查是否可以发送语音.
	CanSendRecord(ctx context.Context, req *entity.CanSendRecordRequest) (*entity.ActionResponse[entity.CanSendRecordResponse], error)
}

// SystemService 状态与运维
type SystemService interface {
	// GetStatus 获取运行状态.
	GetStatus(ctx context.Context, req *entity.GetStatusRequest) (*entity.ActionResponse[entity.GetStatusResponse], error)
	// GetVersionInfo 获取版本信息.
	GetVersionInfo(ctx context.Context, req *entity.GetVersionInfoRequest) (*entity.ActionResponse[entity.GetVersionInfoResponse], error)
	// SetRestart 重启.
	SetRestart(ctx context.Context, req *entity.SetRestartRequest) (*entity.ActionResponse[entity.SetRestartResponse], error)
	// CleanCache 清理缓存.
	CleanCache(ctx context.Context, req *entity.CleanCacheRequest) (*entity.ActionResponse[entity.CleanCacheResponse], error)
}

// OneBotService aggregates all service groups.
type OneBotService interface {
	// 消息服务.
	MessageService
	// 好友与陌生人管理.
	FriendService
	// 群管理.
	GroupAdminService
	// 群信息查询.
	GroupInfoService
	// 账号凭证.
	AccountService
	// 媒体获取.
	MediaService
	// 能力检查.
	CapabilityService
	// 状态与运维.
	SystemService
}

// RegisterGenerated registers actions to dispatcher.
func RegisterGenerated(d *dispatcher.Dispatcher, svc OneBotService) {
	// Group: message
	d.Register("send_private_msg", dispatcher.APIFuncToActionHandler(svc.SendPrivateMsg))
	d.Register("send_group_msg", dispatcher.APIFuncToActionHandler(svc.SendGroupMsg))
	d.Register("send_msg", dispatcher.APIFuncToActionHandler(svc.SendMsg))
	d.Register("delete_msg", dispatcher.APIFuncToActionHandler(svc.DeleteMsg))
	d.Register("get_msg", dispatcher.APIFuncToActionHandler(svc.GetMsg))
	d.Register("get_forward_msg", dispatcher.APIFuncToActionHandler(svc.GetForwardMsg))

	// Group: friend
	d.Register("send_like", dispatcher.APIFuncToActionHandler(svc.SendLike))
	d.Register("set_friend_add_request", dispatcher.APIFuncToActionHandler(svc.SetFriendAddRequest))
	d.Register("get_stranger_info", dispatcher.APIFuncToActionHandler(svc.GetStrangerInfo))
	d.Register("get_friend_list", dispatcher.APIFuncToActionHandler(svc.GetFriendList))

	// Group: group_admin
	d.Register("set_group_kick", dispatcher.APIFuncToActionHandler(svc.SetGroupKick))
	d.Register("set_group_ban", dispatcher.APIFuncToActionHandler(svc.SetGroupBan))
	d.Register("set_group_anonymous_ban", dispatcher.APIFuncToActionHandler(svc.SetGroupAnonymousBan))
	d.Register("set_group_whole_ban", dispatcher.APIFuncToActionHandler(svc.SetGroupWholeBan))
	d.Register("set_group_admin", dispatcher.APIFuncToActionHandler(svc.SetGroupAdmin))
	d.Register("set_group_anonymous", dispatcher.APIFuncToActionHandler(svc.SetGroupAnonymous))
	d.Register("set_group_card", dispatcher.APIFuncToActionHandler(svc.SetGroupCard))
	d.Register("set_group_name", dispatcher.APIFuncToActionHandler(svc.SetGroupName))
	d.Register("set_group_leave", dispatcher.APIFuncToActionHandler(svc.SetGroupLeave))
	d.Register("set_group_special_title", dispatcher.APIFuncToActionHandler(svc.SetGroupSpecialTitle))
	d.Register("set_group_add_request", dispatcher.APIFuncToActionHandler(svc.SetGroupAddRequest))

	// Group: group_info
	d.Register("get_group_info", dispatcher.APIFuncToActionHandler(svc.GetGroupInfo))
	d.Register("get_group_list", dispatcher.APIFuncToActionHandler(svc.GetGroupList))
	d.Register("get_group_member_info", dispatcher.APIFuncToActionHandler(svc.GetGroupMemberInfo))
	d.Register("get_group_member_list", dispatcher.APIFuncToActionHandler(svc.GetGroupMemberList))
	d.Register("get_group_honor_info", dispatcher.APIFuncToActionHandler(svc.GetGroupHonorInfo))

	// Group: account
	d.Register("get_login_info", dispatcher.APIFuncToActionHandler(svc.GetLoginInfo))
	d.Register("get_cookies", dispatcher.APIFuncToActionHandler(svc.GetCookies))
	d.Register("get_csrf_token", dispatcher.APIFuncToActionHandler(svc.GetCsrfToken))
	d.Register("get_credentials", dispatcher.APIFuncToActionHandler(svc.GetCredentials))

	// Group: media
	d.Register("get_record", dispatcher.APIFuncToActionHandler(svc.GetRecord))
	d.Register("get_image", dispatcher.APIFuncToActionHandler(svc.GetImage))

	// Group: capability
	d.Register("can_send_image", dispatcher.APIFuncToActionHandler(svc.CanSendImage))
	d.Register("can_send_record", dispatcher.APIFuncToActionHandler(svc.CanSendRecord))

	// Group: system
	d.Register("get_status", dispatcher.APIFuncToActionHandler(svc.GetStatus))
	d.Register("get_version_info", dispatcher.APIFuncToActionHandler(svc.GetVersionInfo))
	d.Register("set_restart", dispatcher.APIFuncToActionHandler(svc.SetRestart))
	d.Register("clean_cache", dispatcher.APIFuncToActionHandler(svc.CleanCache))

}

// UnimplementedOneBotService aggregates unimplemented group services.
type UnimplementedOneBotService struct {
	UnimplementedMessageService
	UnimplementedFriendService
	UnimplementedGroupAdminService
	UnimplementedGroupInfoService
	UnimplementedAccountService
	UnimplementedMediaService
	UnimplementedCapabilityService
	UnimplementedSystemService
}

// UnimplementedMessageService provides default empty implementations.
type UnimplementedMessageService struct{}

// SendPrivateMsg 发送私聊消息 (unimplemented).
func (*UnimplementedMessageService) SendPrivateMsg(
	ctx context.Context,
	req *entity.SendPrivateMsgRequest,
) (*entity.ActionResponse[entity.SendPrivateMsgResponse], error) {
	panic("unimplemented")
}

// SendGroupMsg 发送群消息 (unimplemented).
func (*UnimplementedMessageService) SendGroupMsg(
	ctx context.Context,
	req *entity.SendGroupMsgRequest,
) (*entity.ActionResponse[entity.SendGroupMsgResponse], error) {
	panic("unimplemented")
}

// SendMsg 发送消息 (unimplemented).
func (*UnimplementedMessageService) SendMsg(
	ctx context.Context,
	req *entity.SendMsgRequest,
) (*entity.ActionResponse[entity.SendMsgResponse], error) {
	panic("unimplemented")
}

// DeleteMsg 撤回消息 (unimplemented).
func (*UnimplementedMessageService) DeleteMsg(
	ctx context.Context,
	req *entity.DeleteMsgRequest,
) (*entity.ActionResponse[entity.DeleteMsgResponse], error) {
	panic("unimplemented")
}

// GetMsg 获取消息 (unimplemented).
func (*UnimplementedMessageService) GetMsg(
	ctx context.Context,
	req *entity.GetMsgRequest,
) (*entity.ActionResponse[entity.GetMsgResponse], error) {
	panic("unimplemented")
}

// GetForwardMsg 获取合并转发消息 (unimplemented).
func (*UnimplementedMessageService) GetForwardMsg(
	ctx context.Context,
	req *entity.GetForwardMsgRequest,
) (*entity.ActionResponse[entity.GetForwardMsgResponse], error) {
	panic("unimplemented")
}

// UnimplementedFriendService provides default empty implementations.
type UnimplementedFriendService struct{}

// SendLike 发送好友赞 (unimplemented).
func (*UnimplementedFriendService) SendLike(
	ctx context.Context,
	req *entity.SendLikeRequest,
) (*entity.ActionResponse[entity.SendLikeResponse], error) {
	panic("unimplemented")
}

// SetFriendAddRequest 处理加好友请求 (unimplemented).
func (*UnimplementedFriendService) SetFriendAddRequest(
	ctx context.Context,
	req *entity.SetFriendAddRequestRequest,
) (*entity.ActionResponse[entity.SetFriendAddRequestResponse], error) {
	panic("unimplemented")
}

// GetStrangerInfo 获取陌生人信息 (unimplemented).
func (*UnimplementedFriendService) GetStrangerInfo(
	ctx context.Context,
	req *entity.GetStrangerInfoRequest,
) (*entity.ActionResponse[entity.GetStrangerInfoResponse], error) {
	panic("unimplemented")
}

// GetFriendList 获取好友列表 (unimplemented).
func (*UnimplementedFriendService) GetFriendList(
	ctx context.Context,
	req *entity.GetFriendListRequest,
) (*entity.ActionResponse[entity.GetFriendListResponse], error) {
	panic("unimplemented")
}

// UnimplementedGroupAdminService provides default empty implementations.
type UnimplementedGroupAdminService struct{}

// SetGroupKick 群组踢人 (unimplemented).
func (*UnimplementedGroupAdminService) SetGroupKick(
	ctx context.Context,
	req *entity.SetGroupKickRequest,
) (*entity.ActionResponse[entity.SetGroupKickResponse], error) {
	panic("unimplemented")
}

// SetGroupBan 群组单人禁言 (unimplemented).
func (*UnimplementedGroupAdminService) SetGroupBan(
	ctx context.Context,
	req *entity.SetGroupBanRequest,
) (*entity.ActionResponse[entity.SetGroupBanResponse], error) {
	panic("unimplemented")
}

// SetGroupAnonymousBan 群组匿名用户禁言 (unimplemented).
func (*UnimplementedGroupAdminService) SetGroupAnonymousBan(
	ctx context.Context,
	req *entity.SetGroupAnonymousBanRequest,
) (*entity.ActionResponse[entity.SetGroupAnonymousBanResponse], error) {
	panic("unimplemented")
}

// SetGroupWholeBan 群组全员禁言 (unimplemented).
func (*UnimplementedGroupAdminService) SetGroupWholeBan(
	ctx context.Context,
	req *entity.SetGroupWholeBanRequest,
) (*entity.ActionResponse[entity.SetGroupWholeBanResponse], error) {
	panic("unimplemented")
}

// SetGroupAdmin 群组设置管理员 (unimplemented).
func (*UnimplementedGroupAdminService) SetGroupAdmin(
	ctx context.Context,
	req *entity.SetGroupAdminRequest,
) (*entity.ActionResponse[entity.SetGroupAdminResponse], error) {
	panic("unimplemented")
}

// SetGroupAnonymous 群组匿名开关 (unimplemented).
func (*UnimplementedGroupAdminService) SetGroupAnonymous(
	ctx context.Context,
	req *entity.SetGroupAnonymousRequest,
) (*entity.ActionResponse[entity.SetGroupAnonymousResponse], error) {
	panic("unimplemented")
}

// SetGroupCard 设置群名片 (unimplemented).
func (*UnimplementedGroupAdminService) SetGroupCard(
	ctx context.Context,
	req *entity.SetGroupCardRequest,
) (*entity.ActionResponse[entity.SetGroupCardResponse], error) {
	panic("unimplemented")
}

// SetGroupName 设置群名 (unimplemented).
func (*UnimplementedGroupAdminService) SetGroupName(
	ctx context.Context,
	req *entity.SetGroupNameRequest,
) (*entity.ActionResponse[entity.SetGroupNameResponse], error) {
	panic("unimplemented")
}

// SetGroupLeave 退出群组 (unimplemented).
func (*UnimplementedGroupAdminService) SetGroupLeave(
	ctx context.Context,
	req *entity.SetGroupLeaveRequest,
) (*entity.ActionResponse[entity.SetGroupLeaveResponse], error) {
	panic("unimplemented")
}

// SetGroupSpecialTitle 设置群组专属头衔 (unimplemented).
func (*UnimplementedGroupAdminService) SetGroupSpecialTitle(
	ctx context.Context,
	req *entity.SetGroupSpecialTitleRequest,
) (*entity.ActionResponse[entity.SetGroupSpecialTitleResponse], error) {
	panic("unimplemented")
}

// SetGroupAddRequest 处理加群请求 (unimplemented).
func (*UnimplementedGroupAdminService) SetGroupAddRequest(
	ctx context.Context,
	req *entity.SetGroupAddRequestRequest,
) (*entity.ActionResponse[entity.SetGroupAddRequestResponse], error) {
	panic("unimplemented")
}

// UnimplementedGroupInfoService provides default empty implementations.
type UnimplementedGroupInfoService struct{}

// GetGroupInfo 获取群信息 (unimplemented).
func (*UnimplementedGroupInfoService) GetGroupInfo(
	ctx context.Context,
	req *entity.GetGroupInfoRequest,
) (*entity.ActionResponse[entity.GetGroupInfoResponse], error) {
	panic("unimplemented")
}

// GetGroupList 获取群列表 (unimplemented).
func (*UnimplementedGroupInfoService) GetGroupList(
	ctx context.Context,
	req *entity.GetGroupListRequest,
) (*entity.ActionResponse[entity.GetGroupListResponse], error) {
	panic("unimplemented")
}

// GetGroupMemberInfo 获取群成员信息 (unimplemented).
func (*UnimplementedGroupInfoService) GetGroupMemberInfo(
	ctx context.Context,
	req *entity.GetGroupMemberInfoRequest,
) (*entity.ActionResponse[entity.GetGroupMemberInfoResponse], error) {
	panic("unimplemented")
}

// GetGroupMemberList 获取群成员列表 (unimplemented).
func (*UnimplementedGroupInfoService) GetGroupMemberList(
	ctx context.Context,
	req *entity.GetGroupMemberListRequest,
) (*entity.ActionResponse[entity.GetGroupMemberListResponse], error) {
	panic("unimplemented")
}

// GetGroupHonorInfo 获取群荣誉信息 (unimplemented).
func (*UnimplementedGroupInfoService) GetGroupHonorInfo(
	ctx context.Context,
	req *entity.GetGroupHonorInfoRequest,
) (*entity.ActionResponse[entity.GetGroupHonorInfoResponse], error) {
	panic("unimplemented")
}

// UnimplementedAccountService provides default empty implementations.
type UnimplementedAccountService struct{}

// GetLoginInfo 获取登录号信息 (unimplemented).
func (*UnimplementedAccountService) GetLoginInfo(
	ctx context.Context,
	req *entity.GetLoginInfoRequest,
) (*entity.ActionResponse[entity.GetLoginInfoResponse], error) {
	panic("unimplemented")
}

// GetCookies 获取 cookies (unimplemented).
func (*UnimplementedAccountService) GetCookies(
	ctx context.Context,
	req *entity.GetCookiesRequest,
) (*entity.ActionResponse[entity.GetCookiesResponse], error) {
	panic("unimplemented")
}

// GetCsrfToken 获取 csrf token (unimplemented).
func (*UnimplementedAccountService) GetCsrfToken(
	ctx context.Context,
	req *entity.GetCsrfTokenRequest,
) (*entity.ActionResponse[entity.GetCsrfTokenResponse], error) {
	panic("unimplemented")
}

// GetCredentials 获取登录凭证 (unimplemented).
func (*UnimplementedAccountService) GetCredentials(
	ctx context.Context,
	req *entity.GetCredentialsRequest,
) (*entity.ActionResponse[entity.GetCredentialsResponse], error) {
	panic("unimplemented")
}

// UnimplementedMediaService provides default empty implementations.
type UnimplementedMediaService struct{}

// GetRecord 获取语音 (unimplemented).
func (*UnimplementedMediaService) GetRecord(
	ctx context.Context,
	req *entity.GetRecordRequest,
) (*entity.ActionResponse[entity.GetRecordResponse], error) {
	panic("unimplemented")
}

// GetImage 获取图片 (unimplemented).
func (*UnimplementedMediaService) GetImage(
	ctx context.Context,
	req *entity.GetImageRequest,
) (*entity.ActionResponse[entity.GetImageResponse], error) {
	panic("unimplemented")
}

// UnimplementedCapabilityService provides default empty implementations.
type UnimplementedCapabilityService struct{}

// CanSendImage 检查是否可以发送图片 (unimplemented).
func (*UnimplementedCapabilityService) CanSendImage(
	ctx context.Context,
	req *entity.CanSendImageRequest,
) (*entity.ActionResponse[entity.CanSendImageResponse], error) {
	panic("unimplemented")
}

// CanSendRecord 检查是否可以发送语音 (unimplemented).
func (*UnimplementedCapabilityService) CanSendRecord(
	ctx context.Context,
	req *entity.CanSendRecordRequest,
) (*entity.ActionResponse[entity.CanSendRecordResponse], error) {
	panic("unimplemented")
}

// UnimplementedSystemService provides default empty implementations.
type UnimplementedSystemService struct{}

// GetStatus 获取运行状态 (unimplemented).
func (*UnimplementedSystemService) GetStatus(
	ctx context.Context,
	req *entity.GetStatusRequest,
) (*entity.ActionResponse[entity.GetStatusResponse], error) {
	panic("unimplemented")
}

// GetVersionInfo 获取版本信息 (unimplemented).
func (*UnimplementedSystemService) GetVersionInfo(
	ctx context.Context,
	req *entity.GetVersionInfoRequest,
) (*entity.ActionResponse[entity.GetVersionInfoResponse], error) {
	panic("unimplemented")
}

// SetRestart 重启 (unimplemented).
func (*UnimplementedSystemService) SetRestart(
	ctx context.Context,
	req *entity.SetRestartRequest,
) (*entity.ActionResponse[entity.SetRestartResponse], error) {
	panic("unimplemented")
}

// CleanCache 清理缓存 (unimplemented).
func (*UnimplementedSystemService) CleanCache(
	ctx context.Context,
	req *entity.CleanCacheRequest,
) (*entity.ActionResponse[entity.CleanCacheResponse], error) {
	panic("unimplemented")
}

var (
	_ OneBotService = (*UnimplementedOneBotService)(nil)

	_ MessageService    = (*UnimplementedMessageService)(nil)
	_ FriendService     = (*UnimplementedFriendService)(nil)
	_ GroupAdminService = (*UnimplementedGroupAdminService)(nil)
	_ GroupInfoService  = (*UnimplementedGroupInfoService)(nil)
	_ AccountService    = (*UnimplementedAccountService)(nil)
	_ MediaService      = (*UnimplementedMediaService)(nil)
	_ CapabilityService = (*UnimplementedCapabilityService)(nil)
	_ SystemService     = (*UnimplementedSystemService)(nil)
)
