// Code generated by onebot-11-go-sdk generator. DO NOT EDIT.
package models

import (
	"encoding/json"
)

// MessageSegment 表示一个通用消息段
// 所有具体的消息段类型都应该能转换为此类型
type MessageSegment struct {
	Type string                 `json:"type"`
	Data map[string]interface{} `json:"data"`
}

// TextSegment 纯文本
// 消息段类型: text
// 支持发送、支持接收
type TextSegment struct {
	// 纯文本内容
	Text string `json:"text,omitempty"`
}

// ToMessageSegment 将 TextSegment 转换为通用 MessageSegment
func (s *TextSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["text"] = s.Text
	return MessageSegment{
		Type: "text",
		Data: data,
	}
}

// FaceSegment QQ 表情
// 消息段类型: face
// 支持发送、支持接收
type FaceSegment struct {
	// QQ 表情 ID | 可能的值: 见 [QQ 表情 ID 表](https://github.com/richardchien/coolq-http-api/wiki/%E8%A1%A8%E6%83%85-CQ-%E7%A0%81-ID-%E8%A1%A8)
	Id string `json:"id,omitempty"`
}

// ToMessageSegment 将 FaceSegment 转换为通用 MessageSegment
func (s *FaceSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["id"] = s.Id
	return MessageSegment{
		Type: "face",
		Data: data,
	}
}

// ImageSegment 图片
// 消息段类型: image
// 支持发送、支持接收
type ImageSegment struct {
	// 图片文件名
	File string `json:"file,omitempty"`
	// 图片类型，`flash` 表示闪照，无此参数表示普通图片 | 可能的值: flash
	Type string `json:"type,omitempty"`
	// 图片 URL
	Url string `json:"url,omitempty"`
	// 只在通过网络 URL 发送时有效，表示是否使用已缓存的文件，默认 `1`
	Cache string `json:"cache,omitempty"`
	// 只在通过网络 URL 发送时有效，表示是否通过代理下载文件（需通过环境变量或配置文件配置代理），默认 `1`
	Proxy string `json:"proxy,omitempty"`
	// 只在通过网络 URL 发送时有效，单位秒，表示下载网络文件的超时时间，默认不超时
	Timeout string `json:"timeout,omitempty"`
}

// ToMessageSegment 将 ImageSegment 转换为通用 MessageSegment
func (s *ImageSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["file"] = s.File
	data["type"] = s.Type
	data["url"] = s.Url
	data["cache"] = s.Cache
	data["proxy"] = s.Proxy
	data["timeout"] = s.Timeout
	return MessageSegment{
		Type: "image",
		Data: data,
	}
}

// RecordSegment 语音
// 消息段类型: record
// 支持发送、支持接收
type RecordSegment struct {
	// 语音文件名
	File string `json:"file,omitempty"`
	// 发送时可选，默认 `0`，设置为 `1` 表示变声 | 可能的值: 0` `1
	Magic string `json:"magic,omitempty"`
	// 语音 URL
	Url string `json:"url,omitempty"`
	// 只在通过网络 URL 发送时有效，表示是否使用已缓存的文件，默认 `1`
	Cache string `json:"cache,omitempty"`
	// 只在通过网络 URL 发送时有效，表示是否通过代理下载文件（需通过环境变量或配置文件配置代理），默认 `1`
	Proxy string `json:"proxy,omitempty"`
	// 只在通过网络 URL 发送时有效，单位秒，表示下载网络文件的超时时间 ，默认不超时
	Timeout string `json:"timeout,omitempty"`
}

// ToMessageSegment 将 RecordSegment 转换为通用 MessageSegment
func (s *RecordSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["file"] = s.File
	data["magic"] = s.Magic
	data["url"] = s.Url
	data["cache"] = s.Cache
	data["proxy"] = s.Proxy
	data["timeout"] = s.Timeout
	return MessageSegment{
		Type: "record",
		Data: data,
	}
}

// VideoSegment 短视频
// 消息段类型: video
// 支持发送、支持接收
type VideoSegment struct {
	// 视频文件名
	File string `json:"file,omitempty"`
	// 视频 URL
	Url string `json:"url,omitempty"`
	// 只在通过网络 URL 发送时有效，表示是否使用已缓存的文件，默认 `1`
	Cache string `json:"cache,omitempty"`
	// 只在通过网络 URL 发送时有效，表示是否通过代理下载文件（需通过环境变量或配置文件配置代理），默认 `1`
	Proxy string `json:"proxy,omitempty"`
	// 只在通过网络 URL 发送时有效，单位秒，表示下载网络文件的超时时间 ，默认不超时
	Timeout string `json:"timeout,omitempty"`
}

// ToMessageSegment 将 VideoSegment 转换为通用 MessageSegment
func (s *VideoSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["file"] = s.File
	data["url"] = s.Url
	data["cache"] = s.Cache
	data["proxy"] = s.Proxy
	data["timeout"] = s.Timeout
	return MessageSegment{
		Type: "video",
		Data: data,
	}
}

// AtSegment @某人
// 消息段类型: at
// 支持发送、支持接收
type AtSegment struct {
	// @的 QQ 号，`all` 表示全体成员 | 可能的值: QQ 号, all
	Qq string `json:"qq,omitempty"`
}

// ToMessageSegment 将 AtSegment 转换为通用 MessageSegment
func (s *AtSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["qq"] = s.Qq
	return MessageSegment{
		Type: "at",
		Data: data,
	}
}

// RpsSegment 猜拳魔法表情
// 消息段类型: rps
// 支持发送、支持接收
type RpsSegment struct {
	// 无参数
}

// ToMessageSegment 将 RpsSegment 转换为通用 MessageSegment
func (s *RpsSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	return MessageSegment{
		Type: "rps",
		Data: data,
	}
}

// DiceSegment 掷骰子魔法表情
// 消息段类型: dice
// 支持发送、支持接收
type DiceSegment struct {
	// 无参数
}

// ToMessageSegment 将 DiceSegment 转换为通用 MessageSegment
func (s *DiceSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	return MessageSegment{
		Type: "dice",
		Data: data,
	}
}

// ShakeSegment 窗口抖动（戳一戳）
// 消息段类型: shake
// 支持发送
type ShakeSegment struct {
	// 无参数
}

// ToMessageSegment 将 ShakeSegment 转换为通用 MessageSegment
func (s *ShakeSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	return MessageSegment{
		Type: "shake",
		Data: data,
	}
}

// PokeSegment 戳一戳
// 消息段类型: poke
// 支持发送、支持接收
type PokeSegment struct {
	// 类型 | 可能的值: 见 [Mirai 的 PokeMessage 类](https://github.com/mamoe/mirai/blob/f5eefae7ecee84d18a66afce3f89b89fe1584b78/mirai-core/src/commonMain/kotlin/net.mamoe.mirai/message/data/HummerMessage.kt#L49)
	Type string `json:"type,omitempty"`
	// ID | 可能的值: 同上
	Id string `json:"id,omitempty"`
	// 表情名
	Name string `json:"name,omitempty"`
}

// ToMessageSegment 将 PokeSegment 转换为通用 MessageSegment
func (s *PokeSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["type"] = s.Type
	data["id"] = s.Id
	data["name"] = s.Name
	return MessageSegment{
		Type: "poke",
		Data: data,
	}
}

// AnonymousSegment 匿名发消息
// 消息段类型: anonymous
// 支持发送
type AnonymousSegment struct {
	// 可选，表示无法匿名时是否继续发送
	Ignore string `json:"ignore,omitempty"`
}

// ToMessageSegment 将 AnonymousSegment 转换为通用 MessageSegment
func (s *AnonymousSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["ignore"] = s.Ignore
	return MessageSegment{
		Type: "anonymous",
		Data: data,
	}
}

// ShareSegment 链接分享
// 消息段类型: share
// 支持发送、支持接收
type ShareSegment struct {
	// URL
	Url string `json:"url,omitempty"`
	// 标题
	Title string `json:"title,omitempty"`
	// 发送时可选，内容描述
	Content string `json:"content,omitempty"`
	// 发送时可选，图片 URL
	Image string `json:"image,omitempty"`
}

// ToMessageSegment 将 ShareSegment 转换为通用 MessageSegment
func (s *ShareSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["url"] = s.Url
	data["title"] = s.Title
	data["content"] = s.Content
	data["image"] = s.Image
	return MessageSegment{
		Type: "share",
		Data: data,
	}
}

// ContactSegment 推荐好友
// 消息段类型: contact
// 支持发送、支持接收
type ContactSegment struct {
	// 推荐好友 | 可能的值: qq
	Type string `json:"type,omitempty"`
	// 被推荐人的 QQ 号
	Id string `json:"id,omitempty"`
}

// ToMessageSegment 将 ContactSegment 转换为通用 MessageSegment
func (s *ContactSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["type"] = s.Type
	data["id"] = s.Id
	return MessageSegment{
		Type: "contact",
		Data: data,
	}
}

// ContactSegment 推荐群
// 消息段类型: contact
// 支持发送、支持接收
type ContactSegment struct {
	// 推荐群 | 可能的值: group
	Type string `json:"type,omitempty"`
	// 被推荐群的群号
	Id string `json:"id,omitempty"`
}

// ToMessageSegment 将 ContactSegment 转换为通用 MessageSegment
func (s *ContactSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["type"] = s.Type
	data["id"] = s.Id
	return MessageSegment{
		Type: "contact",
		Data: data,
	}
}

// LocationSegment 位置
// 消息段类型: location
// 支持发送、支持接收
type LocationSegment struct {
	// 纬度
	Lat string `json:"lat,omitempty"`
	// 经度
	Lon string `json:"lon,omitempty"`
	// 发送时可选，标题
	Title string `json:"title,omitempty"`
	// 发送时可选，内容描述
	Content string `json:"content,omitempty"`
}

// ToMessageSegment 将 LocationSegment 转换为通用 MessageSegment
func (s *LocationSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["lat"] = s.Lat
	data["lon"] = s.Lon
	data["title"] = s.Title
	data["content"] = s.Content
	return MessageSegment{
		Type: "location",
		Data: data,
	}
}

// MusicSegment 音乐分享
// 消息段类型: music
// 支持发送
type MusicSegment struct {
	// 分别表示使用 QQ 音乐、网易云音乐、虾米音乐
	Type string `json:"type,omitempty"`
	// 歌曲 ID
	Id string `json:"id,omitempty"`
}

// ToMessageSegment 将 MusicSegment 转换为通用 MessageSegment
func (s *MusicSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["type"] = s.Type
	data["id"] = s.Id
	return MessageSegment{
		Type: "music",
		Data: data,
	}
}

// MusicSegment 音乐自定义分享
// 消息段类型: music
// 支持发送
type MusicSegment struct {
	// 表示音乐自定义分享
	Type string `json:"type,omitempty"`
	// 点击后跳转目标 URL
	Url string `json:"url,omitempty"`
	// 音乐 URL
	Audio string `json:"audio,omitempty"`
	// 标题
	Title string `json:"title,omitempty"`
	// 发送时可选，内容描述
	Content string `json:"content,omitempty"`
	// 发送时可选，图片 URL
	Image string `json:"image,omitempty"`
}

// ToMessageSegment 将 MusicSegment 转换为通用 MessageSegment
func (s *MusicSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["type"] = s.Type
	data["url"] = s.Url
	data["audio"] = s.Audio
	data["title"] = s.Title
	data["content"] = s.Content
	data["image"] = s.Image
	return MessageSegment{
		Type: "music",
		Data: data,
	}
}

// ReplySegment 回复
// 消息段类型: reply
// 支持发送、支持接收
type ReplySegment struct {
	// 回复时引用的消息 ID
	Id string `json:"id,omitempty"`
}

// ToMessageSegment 将 ReplySegment 转换为通用 MessageSegment
func (s *ReplySegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["id"] = s.Id
	return MessageSegment{
		Type: "reply",
		Data: data,
	}
}

// ForwardSegment 合并转发
// 消息段类型: forward
// 支持接收
type ForwardSegment struct {
	// 合并转发 ID，需通过 [`get_forward_msg` API](../api/public.md#get_forward_msg-获取合并转发消息) 获取具体内容
	Id string `json:"id,omitempty"`
}

// ToMessageSegment 将 ForwardSegment 转换为通用 MessageSegment
func (s *ForwardSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["id"] = s.Id
	return MessageSegment{
		Type: "forward",
		Data: data,
	}
}

// NodeSegment 合并转发节点
// 消息段类型: node
// 支持发送
type NodeSegment struct {
	// 转发的消息 ID
	Id string `json:"id,omitempty"`
}

// ToMessageSegment 将 NodeSegment 转换为通用 MessageSegment
func (s *NodeSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["id"] = s.Id
	return MessageSegment{
		Type: "node",
		Data: data,
	}
}

// NodeSegment 合并转发自定义节点
// 消息段类型: node
// 支持发送、支持接收
type NodeSegment struct {
	// 发送者 QQ 号
	UserId string `json:"user_id,omitempty"`
	// 发送者昵称
	Nickname string `json:"nickname,omitempty"`
	// 消息内容，支持发送消息时的 `message` 数据类型，见 [API 的参数](../api/#参数)
	Content string `json:"content,omitempty"`
}

// ToMessageSegment 将 NodeSegment 转换为通用 MessageSegment
func (s *NodeSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["user_id"] = s.UserId
	data["nickname"] = s.Nickname
	data["content"] = s.Content
	return MessageSegment{
		Type: "node",
		Data: data,
	}
}

// XmlSegment XML 消息
// 消息段类型: xml
// 支持发送、支持接收
type XmlSegment struct {
	// XML 内容
	Data string `json:"data,omitempty"`
}

// ToMessageSegment 将 XmlSegment 转换为通用 MessageSegment
func (s *XmlSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["data"] = s.Data
	return MessageSegment{
		Type: "xml",
		Data: data,
	}
}

// JsonSegment JSON 消息
// 消息段类型: json
// 支持发送、支持接收
type JsonSegment struct {
	// JSON 内容
	Data string `json:"data,omitempty"`
}

// ToMessageSegment 将 JsonSegment 转换为通用 MessageSegment
func (s *JsonSegment) ToMessageSegment() MessageSegment {
	data := make(map[string]interface{})
	data["data"] = s.Data
	return MessageSegment{
		Type: "json",
		Data: data,
	}
}

// NewTextSegment 创建文本消息段
func NewTextSegment(text string) MessageSegment {
	return MessageSegment{
		Type: "text",
		Data: map[string]interface{}{"text": text},
	}
}

// NewImageSegment 创建图片消息段
func NewImageSegment(file string) MessageSegment {
	return MessageSegment{
		Type: "image",
		Data: map[string]interface{}{"file": file},
	}
}

// NewAtSegment 创建 @ 消息段
func NewAtSegment(qq string) MessageSegment {
	return MessageSegment{
		Type: "at",
		Data: map[string]interface{}{"qq": qq},
	}
}
