// Code generated by entity-gen. DO NOT EDIT.

package entity

// GetUserId
// 对方 QQ 号
func (r *SendPrivateMsgRequest) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 对方 QQ 号
func (r *SendPrivateMsgRequest) SetUserId(v int64) *SendPrivateMsgRequest {
	r.UserId = v
	return r
}

// GetMessage
// 要发送的内容
// 可以是字符串 (CQ 码格式) 或消息段数组
func (r *SendPrivateMsgRequest) GetMessage() *MessageValue {
	if r == nil {
		var zero *MessageValue
		return zero
	}
	return r.Message
}

// SetMessage
// 要发送的内容
// 可以是字符串 (CQ 码格式) 或消息段数组
func (r *SendPrivateMsgRequest) SetMessage(v *MessageValue) *SendPrivateMsgRequest {
	r.Message = v
	return r
}

// GetAutoEscape
// 消息内容是否作为纯文本发送（即不解析 CQ 码），只在 `message` 字段是字符串时有效 | 可能的值: false
func (r *SendPrivateMsgRequest) GetAutoEscape() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.AutoEscape
}

// SetAutoEscape
// 消息内容是否作为纯文本发送（即不解析 CQ 码），只在 `message` 字段是字符串时有效 | 可能的值: false
func (r *SendPrivateMsgRequest) SetAutoEscape(v bool) *SendPrivateMsgRequest {
	r.AutoEscape = v
	return r
}

// GetMessageId
// 消息 ID
func (r *SendPrivateMsgResponse) GetMessageId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.MessageId
}

// SetMessageId
// 消息 ID
func (r *SendPrivateMsgResponse) SetMessageId(v int64) *SendPrivateMsgResponse {
	r.MessageId = v
	return r
}

// GetGroupId
// 群号
func (r *SendGroupMsgRequest) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *SendGroupMsgRequest) SetGroupId(v int64) *SendGroupMsgRequest {
	r.GroupId = v
	return r
}

// GetMessage
// 要发送的内容
// 可以是字符串 (CQ 码格式) 或消息段数组
func (r *SendGroupMsgRequest) GetMessage() *MessageValue {
	if r == nil {
		var zero *MessageValue
		return zero
	}
	return r.Message
}

// SetMessage
// 要发送的内容
// 可以是字符串 (CQ 码格式) 或消息段数组
func (r *SendGroupMsgRequest) SetMessage(v *MessageValue) *SendGroupMsgRequest {
	r.Message = v
	return r
}

// GetAutoEscape
// 消息内容是否作为纯文本发送（即不解析 CQ 码），只在 `message` 字段是字符串时有效 | 可能的值: false
func (r *SendGroupMsgRequest) GetAutoEscape() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.AutoEscape
}

// SetAutoEscape
// 消息内容是否作为纯文本发送（即不解析 CQ 码），只在 `message` 字段是字符串时有效 | 可能的值: false
func (r *SendGroupMsgRequest) SetAutoEscape(v bool) *SendGroupMsgRequest {
	r.AutoEscape = v
	return r
}

// GetMessageId
// 消息 ID
func (r *SendGroupMsgResponse) GetMessageId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.MessageId
}

// SetMessageId
// 消息 ID
func (r *SendGroupMsgResponse) SetMessageId(v int64) *SendGroupMsgResponse {
	r.MessageId = v
	return r
}

// GetMessageType
// 消息类型，支持 `private`、`group`，分别对应私聊、群组，如不传入，则根据传入的 `*_id` 参数判断
func (r *SendMsgRequest) GetMessageType() MessageType {
	if r == nil {
		var zero MessageType
		return zero
	}
	return r.MessageType
}

// SetMessageType
// 消息类型，支持 `private`、`group`，分别对应私聊、群组，如不传入，则根据传入的 `*_id` 参数判断
func (r *SendMsgRequest) SetMessageType(v MessageType) *SendMsgRequest {
	r.MessageType = v
	return r
}

// GetUserId
// 对方 QQ 号（消息类型为 `private` 时需要）
func (r *SendMsgRequest) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 对方 QQ 号（消息类型为 `private` 时需要）
func (r *SendMsgRequest) SetUserId(v int64) *SendMsgRequest {
	r.UserId = v
	return r
}

// GetGroupId
// 群号（消息类型为 `group` 时需要）
func (r *SendMsgRequest) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号（消息类型为 `group` 时需要）
func (r *SendMsgRequest) SetGroupId(v int64) *SendMsgRequest {
	r.GroupId = v
	return r
}

// GetMessage
// 要发送的内容
// 可以是字符串 (CQ 码格式) 或消息段数组
func (r *SendMsgRequest) GetMessage() *MessageValue {
	if r == nil {
		var zero *MessageValue
		return zero
	}
	return r.Message
}

// SetMessage
// 要发送的内容
// 可以是字符串 (CQ 码格式) 或消息段数组
func (r *SendMsgRequest) SetMessage(v *MessageValue) *SendMsgRequest {
	r.Message = v
	return r
}

// GetAutoEscape
// 消息内容是否作为纯文本发送（即不解析 CQ 码），只在 `message` 字段是字符串时有效 | 可能的值: false
func (r *SendMsgRequest) GetAutoEscape() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.AutoEscape
}

// SetAutoEscape
// 消息内容是否作为纯文本发送（即不解析 CQ 码），只在 `message` 字段是字符串时有效 | 可能的值: false
func (r *SendMsgRequest) SetAutoEscape(v bool) *SendMsgRequest {
	r.AutoEscape = v
	return r
}

// GetMessageId
// 消息 ID
func (r *SendMsgResponse) GetMessageId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.MessageId
}

// SetMessageId
// 消息 ID
func (r *SendMsgResponse) SetMessageId(v int64) *SendMsgResponse {
	r.MessageId = v
	return r
}

// GetMessageId
// 消息 ID
func (r *DeleteMsgRequest) GetMessageId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.MessageId
}

// SetMessageId
// 消息 ID
func (r *DeleteMsgRequest) SetMessageId(v int64) *DeleteMsgRequest {
	r.MessageId = v
	return r
}

// GetUserId
// QQ 号
func (r *BaseUser) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// QQ 号
func (r *BaseUser) SetUserId(v int64) *BaseUser {
	r.UserId = v
	return r
}

// GetNickname
// 昵称
func (r *BaseUser) GetNickname() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Nickname
}

// SetNickname
// 昵称
func (r *BaseUser) SetNickname(v string) *BaseUser {
	r.Nickname = v
	return r
}

// GetSex
// 性别，`male` 或 `female` 或 `unknown`
func (r *BaseUser) GetSex() SexType {
	if r == nil {
		var zero SexType
		return zero
	}
	return r.Sex
}

// SetSex
// 性别，`male` 或 `female` 或 `unknown`
func (r *BaseUser) SetSex(v SexType) *BaseUser {
	r.Sex = v
	return r
}

// GetAge
// 年龄
func (r *BaseUser) GetAge() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Age
}

// SetAge
// 年龄
func (r *BaseUser) SetAge(v int64) *BaseUser {
	r.Age = v
	return r
}

// GetRemark
// 备注名
func (r *BaseUser) GetRemark() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Remark
}

// SetRemark
// 备注名
func (r *BaseUser) SetRemark(v string) *BaseUser {
	r.Remark = v
	return r
}

// GetMessageId
// 消息 ID
func (r *GetMsgRequest) GetMessageId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.MessageId
}

// SetMessageId
// 消息 ID
func (r *GetMsgRequest) SetMessageId(v int64) *GetMsgRequest {
	r.MessageId = v
	return r
}

// GetTime
// 发送时间
func (r *GetMsgResponse) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 发送时间
func (r *GetMsgResponse) SetTime(v int64) *GetMsgResponse {
	r.Time = v
	return r
}

// GetMessageType
// 消息类型，同 [消息事件](../event/message.md)
func (r *GetMsgResponse) GetMessageType() MessageType {
	if r == nil {
		var zero MessageType
		return zero
	}
	return r.MessageType
}

// SetMessageType
// 消息类型，同 [消息事件](../event/message.md)
func (r *GetMsgResponse) SetMessageType(v MessageType) *GetMsgResponse {
	r.MessageType = v
	return r
}

// GetMessageId
// 消息 ID
func (r *GetMsgResponse) GetMessageId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.MessageId
}

// SetMessageId
// 消息 ID
func (r *GetMsgResponse) SetMessageId(v int64) *GetMsgResponse {
	r.MessageId = v
	return r
}

// GetRealId
// 消息真实 ID
func (r *GetMsgResponse) GetRealId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.RealId
}

// SetRealId
// 消息真实 ID
func (r *GetMsgResponse) SetRealId(v int64) *GetMsgResponse {
	r.RealId = v
	return r
}

// GetSender
// 发送人信息，同 [消息事件](../event/message.md)
func (r *GetMsgResponse) GetSender() *BaseUser {
	if r == nil {
		var zero *BaseUser
		return zero
	}
	return r.Sender
}

// SetSender
// 发送人信息，同 [消息事件](../event/message.md)
func (r *GetMsgResponse) SetSender(v *BaseUser) *GetMsgResponse {
	r.Sender = v
	return r
}

// GetMessage
// 消息内容
// 可以是字符串 (CQ 码格式) 或消息段数组
func (r *GetMsgResponse) GetMessage() *MessageValue {
	if r == nil {
		var zero *MessageValue
		return zero
	}
	return r.Message
}

// SetMessage
// 消息内容
// 可以是字符串 (CQ 码格式) 或消息段数组
func (r *GetMsgResponse) SetMessage(v *MessageValue) *GetMsgResponse {
	r.Message = v
	return r
}

// GetId
// 合并转发 ID
func (r *GetForwardMsgRequest) GetId() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Id
}

// SetId
// 合并转发 ID
func (r *GetForwardMsgRequest) SetId(v string) *GetForwardMsgRequest {
	r.Id = v
	return r
}

// GetMessage
// 消息内容，使用 [消息的数组格式](../message/array.md) 表示，数组中的消息段全部为 [`node` 消息段](../message/segment.md#合并转发自定义节点)
// 可以是字符串 (CQ 码格式) 或消息段数组
func (r *GetForwardMsgResponse) GetMessage() *MessageValue {
	if r == nil {
		var zero *MessageValue
		return zero
	}
	return r.Message
}

// SetMessage
// 消息内容，使用 [消息的数组格式](../message/array.md) 表示，数组中的消息段全部为 [`node` 消息段](../message/segment.md#合并转发自定义节点)
// 可以是字符串 (CQ 码格式) 或消息段数组
func (r *GetForwardMsgResponse) SetMessage(v *MessageValue) *GetForwardMsgResponse {
	r.Message = v
	return r
}

// GetUserId
// 对方 QQ 号
func (r *SendLikeRequest) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 对方 QQ 号
func (r *SendLikeRequest) SetUserId(v int64) *SendLikeRequest {
	r.UserId = v
	return r
}

// GetTimes
// 赞的次数，每个好友每天最多 10 次 | 默认值: 1
func (r *SendLikeRequest) GetTimes() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Times
}

// SetTimes
// 赞的次数，每个好友每天最多 10 次 | 默认值: 1
func (r *SendLikeRequest) SetTimes(v int64) *SendLikeRequest {
	r.Times = v
	return r
}

// GetGroupId
// 群号
func (r *SetGroupKickRequest) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *SetGroupKickRequest) SetGroupId(v int64) *SetGroupKickRequest {
	r.GroupId = v
	return r
}

// GetUserId
// 要踢的 QQ 号
func (r *SetGroupKickRequest) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 要踢的 QQ 号
func (r *SetGroupKickRequest) SetUserId(v int64) *SetGroupKickRequest {
	r.UserId = v
	return r
}

// GetRejectAddRequest
// 拒绝此人的加群请求 | 可能的值: false
func (r *SetGroupKickRequest) GetRejectAddRequest() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.RejectAddRequest
}

// SetRejectAddRequest
// 拒绝此人的加群请求 | 可能的值: false
func (r *SetGroupKickRequest) SetRejectAddRequest(v bool) *SetGroupKickRequest {
	r.RejectAddRequest = v
	return r
}

// GetGroupId
// 群号
func (r *SetGroupBanRequest) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *SetGroupBanRequest) SetGroupId(v int64) *SetGroupBanRequest {
	r.GroupId = v
	return r
}

// GetUserId
// 要禁言的 QQ 号
func (r *SetGroupBanRequest) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 要禁言的 QQ 号
func (r *SetGroupBanRequest) SetUserId(v int64) *SetGroupBanRequest {
	r.UserId = v
	return r
}

// GetDuration
// 禁言时长，单位秒，0 表示取消禁言 | 可能的值: 30 * 60
func (r *SetGroupBanRequest) GetDuration() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Duration
}

// SetDuration
// 禁言时长，单位秒，0 表示取消禁言 | 可能的值: 30 * 60
func (r *SetGroupBanRequest) SetDuration(v int64) *SetGroupBanRequest {
	r.Duration = v
	return r
}

// GetGroupId
// 群号
func (r *SetGroupAnonymousBanRequest) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *SetGroupAnonymousBanRequest) SetGroupId(v int64) *SetGroupAnonymousBanRequest {
	r.GroupId = v
	return r
}

// GetAnonymous
// 可选，要禁言的匿名用户对象（群消息上报的 `anonymous` 字段）
func (r *SetGroupAnonymousBanRequest) GetAnonymous() *GroupAnonymousUser {
	if r == nil {
		var zero *GroupAnonymousUser
		return zero
	}
	return r.Anonymous
}

// SetAnonymous
// 可选，要禁言的匿名用户对象（群消息上报的 `anonymous` 字段）
func (r *SetGroupAnonymousBanRequest) SetAnonymous(v *GroupAnonymousUser) *SetGroupAnonymousBanRequest {
	r.Anonymous = v
	return r
}

// GetAnonymousFlag
// 可选，要禁言的匿名用户的 flag（需从群消息上报的数据中获得）
func (r *SetGroupAnonymousBanRequest) GetAnonymousFlag() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.AnonymousFlag
}

// SetAnonymousFlag
// 可选，要禁言的匿名用户的 flag（需从群消息上报的数据中获得）
func (r *SetGroupAnonymousBanRequest) SetAnonymousFlag(v string) *SetGroupAnonymousBanRequest {
	r.AnonymousFlag = v
	return r
}

// GetDuration
// 禁言时长，单位秒，无法取消匿名用户禁言 | 可能的值: 30 * 60
func (r *SetGroupAnonymousBanRequest) GetDuration() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Duration
}

// SetDuration
// 禁言时长，单位秒，无法取消匿名用户禁言 | 可能的值: 30 * 60
func (r *SetGroupAnonymousBanRequest) SetDuration(v int64) *SetGroupAnonymousBanRequest {
	r.Duration = v
	return r
}

// GetGroupId
// 群号
func (r *SetGroupWholeBanRequest) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *SetGroupWholeBanRequest) SetGroupId(v int64) *SetGroupWholeBanRequest {
	r.GroupId = v
	return r
}

// GetEnable
// 是否禁言 | 可能的值: true
func (r *SetGroupWholeBanRequest) GetEnable() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.Enable
}

// SetEnable
// 是否禁言 | 可能的值: true
func (r *SetGroupWholeBanRequest) SetEnable(v bool) *SetGroupWholeBanRequest {
	r.Enable = v
	return r
}

// GetGroupId
// 群号
func (r *SetGroupAdminRequest) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *SetGroupAdminRequest) SetGroupId(v int64) *SetGroupAdminRequest {
	r.GroupId = v
	return r
}

// GetUserId
// 要设置管理员的 QQ 号
func (r *SetGroupAdminRequest) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 要设置管理员的 QQ 号
func (r *SetGroupAdminRequest) SetUserId(v int64) *SetGroupAdminRequest {
	r.UserId = v
	return r
}

// GetEnable
// true 为设置，false 为取消 | 可能的值: true
func (r *SetGroupAdminRequest) GetEnable() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.Enable
}

// SetEnable
// true 为设置，false 为取消 | 可能的值: true
func (r *SetGroupAdminRequest) SetEnable(v bool) *SetGroupAdminRequest {
	r.Enable = v
	return r
}

// GetGroupId
// 群号
func (r *SetGroupAnonymousRequest) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *SetGroupAnonymousRequest) SetGroupId(v int64) *SetGroupAnonymousRequest {
	r.GroupId = v
	return r
}

// GetEnable
// 是否允许匿名聊天 | 可能的值: true
func (r *SetGroupAnonymousRequest) GetEnable() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.Enable
}

// SetEnable
// 是否允许匿名聊天 | 可能的值: true
func (r *SetGroupAnonymousRequest) SetEnable(v bool) *SetGroupAnonymousRequest {
	r.Enable = v
	return r
}

// GetGroupId
// 群号
func (r *SetGroupCardRequest) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *SetGroupCardRequest) SetGroupId(v int64) *SetGroupCardRequest {
	r.GroupId = v
	return r
}

// GetUserId
// 要设置的 QQ 号
func (r *SetGroupCardRequest) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 要设置的 QQ 号
func (r *SetGroupCardRequest) SetUserId(v int64) *SetGroupCardRequest {
	r.UserId = v
	return r
}

// GetCard
// 群名片内容，不填或空字符串表示删除群名片 | 默认值: 空
func (r *SetGroupCardRequest) GetCard() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Card
}

// SetCard
// 群名片内容，不填或空字符串表示删除群名片 | 默认值: 空
func (r *SetGroupCardRequest) SetCard(v string) *SetGroupCardRequest {
	r.Card = v
	return r
}

// GetGroupId
// 群号
func (r *SetGroupNameRequest) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *SetGroupNameRequest) SetGroupId(v int64) *SetGroupNameRequest {
	r.GroupId = v
	return r
}

// GetGroupName
// 新群名
func (r *SetGroupNameRequest) GetGroupName() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.GroupName
}

// SetGroupName
// 新群名
func (r *SetGroupNameRequest) SetGroupName(v string) *SetGroupNameRequest {
	r.GroupName = v
	return r
}

// GetGroupId
// 群号
func (r *SetGroupLeaveRequest) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *SetGroupLeaveRequest) SetGroupId(v int64) *SetGroupLeaveRequest {
	r.GroupId = v
	return r
}

// GetIsDismiss
// 是否解散，如果登录号是群主，则仅在此项为 true 时能够解散 | 可能的值: false
func (r *SetGroupLeaveRequest) GetIsDismiss() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.IsDismiss
}

// SetIsDismiss
// 是否解散，如果登录号是群主，则仅在此项为 true 时能够解散 | 可能的值: false
func (r *SetGroupLeaveRequest) SetIsDismiss(v bool) *SetGroupLeaveRequest {
	r.IsDismiss = v
	return r
}

// GetGroupId
// 群号
func (r *SetGroupSpecialTitleRequest) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *SetGroupSpecialTitleRequest) SetGroupId(v int64) *SetGroupSpecialTitleRequest {
	r.GroupId = v
	return r
}

// GetUserId
// 要设置的 QQ 号
func (r *SetGroupSpecialTitleRequest) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 要设置的 QQ 号
func (r *SetGroupSpecialTitleRequest) SetUserId(v int64) *SetGroupSpecialTitleRequest {
	r.UserId = v
	return r
}

// GetSpecialTitle
// 专属头衔，不填或空字符串表示删除专属头衔 | 默认值: 空
func (r *SetGroupSpecialTitleRequest) GetSpecialTitle() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.SpecialTitle
}

// SetSpecialTitle
// 专属头衔，不填或空字符串表示删除专属头衔 | 默认值: 空
func (r *SetGroupSpecialTitleRequest) SetSpecialTitle(v string) *SetGroupSpecialTitleRequest {
	r.SpecialTitle = v
	return r
}

// GetDuration
// 专属头衔有效期，单位秒，-1 表示永久，不过此项似乎没有效果，可能是只有某些特殊的时间长度有效，有待测试 | 可能的值: -1
func (r *SetGroupSpecialTitleRequest) GetDuration() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Duration
}

// SetDuration
// 专属头衔有效期，单位秒，-1 表示永久，不过此项似乎没有效果，可能是只有某些特殊的时间长度有效，有待测试 | 可能的值: -1
func (r *SetGroupSpecialTitleRequest) SetDuration(v int64) *SetGroupSpecialTitleRequest {
	r.Duration = v
	return r
}

// GetFlag
// 加好友请求的 flag（需从上报的数据中获得）
func (r *SetFriendAddRequestRequest) GetFlag() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Flag
}

// SetFlag
// 加好友请求的 flag（需从上报的数据中获得）
func (r *SetFriendAddRequestRequest) SetFlag(v string) *SetFriendAddRequestRequest {
	r.Flag = v
	return r
}

// GetApprove
// 是否同意请求 | 可能的值: true
func (r *SetFriendAddRequestRequest) GetApprove() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.Approve
}

// SetApprove
// 是否同意请求 | 可能的值: true
func (r *SetFriendAddRequestRequest) SetApprove(v bool) *SetFriendAddRequestRequest {
	r.Approve = v
	return r
}

// GetRemark
// 添加后的好友备注（仅在同意时有效） | 默认值: 空
func (r *SetFriendAddRequestRequest) GetRemark() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Remark
}

// SetRemark
// 添加后的好友备注（仅在同意时有效） | 默认值: 空
func (r *SetFriendAddRequestRequest) SetRemark(v string) *SetFriendAddRequestRequest {
	r.Remark = v
	return r
}

// GetFlag
// 加群请求的 flag（需从上报的数据中获得）
func (r *SetGroupAddRequestRequest) GetFlag() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Flag
}

// SetFlag
// 加群请求的 flag（需从上报的数据中获得）
func (r *SetGroupAddRequestRequest) SetFlag(v string) *SetGroupAddRequestRequest {
	r.Flag = v
	return r
}

// GetSubType
// `add` 或 `invite`，请求类型（需要和上报消息中的 `sub_type` 字段相符）
func (r *SetGroupAddRequestRequest) GetSubType() SetGroupAddRequestSubType {
	if r == nil {
		var zero SetGroupAddRequestSubType
		return zero
	}
	return r.SubType
}

// SetSubType
// `add` 或 `invite`，请求类型（需要和上报消息中的 `sub_type` 字段相符）
func (r *SetGroupAddRequestRequest) SetSubType(v SetGroupAddRequestSubType) *SetGroupAddRequestRequest {
	r.SubType = v
	return r
}

// GetApprove
// 是否同意请求／邀请 | 可能的值: true
func (r *SetGroupAddRequestRequest) GetApprove() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.Approve
}

// SetApprove
// 是否同意请求／邀请 | 可能的值: true
func (r *SetGroupAddRequestRequest) SetApprove(v bool) *SetGroupAddRequestRequest {
	r.Approve = v
	return r
}

// GetReason
// 拒绝理由（仅在拒绝时有效） | 默认值: 空
func (r *SetGroupAddRequestRequest) GetReason() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Reason
}

// SetReason
// 拒绝理由（仅在拒绝时有效） | 默认值: 空
func (r *SetGroupAddRequestRequest) SetReason(v string) *SetGroupAddRequestRequest {
	r.Reason = v
	return r
}

// GetUserId
// QQ 号
func (r *GetLoginInfoResponse) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// QQ 号
func (r *GetLoginInfoResponse) SetUserId(v int64) *GetLoginInfoResponse {
	r.UserId = v
	return r
}

// GetNickname
// QQ 昵称
func (r *GetLoginInfoResponse) GetNickname() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Nickname
}

// SetNickname
// QQ 昵称
func (r *GetLoginInfoResponse) SetNickname(v string) *GetLoginInfoResponse {
	r.Nickname = v
	return r
}

// GetUserId
// QQ 号
func (r *GetStrangerInfoRequest) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// QQ 号
func (r *GetStrangerInfoRequest) SetUserId(v int64) *GetStrangerInfoRequest {
	r.UserId = v
	return r
}

// GetNoCache
// 是否不使用缓存（使用缓存可能更新不及时，但响应更快） | 可能的值: false
func (r *GetStrangerInfoRequest) GetNoCache() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.NoCache
}

// SetNoCache
// 是否不使用缓存（使用缓存可能更新不及时，但响应更快） | 可能的值: false
func (r *GetStrangerInfoRequest) SetNoCache(v bool) *GetStrangerInfoRequest {
	r.NoCache = v
	return r
}

// GetUserId
// QQ 号
func (r *GetStrangerInfoResponse) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// QQ 号
func (r *GetStrangerInfoResponse) SetUserId(v int64) *GetStrangerInfoResponse {
	r.UserId = v
	return r
}

// GetNickname
// 昵称
func (r *GetStrangerInfoResponse) GetNickname() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Nickname
}

// SetNickname
// 昵称
func (r *GetStrangerInfoResponse) SetNickname(v string) *GetStrangerInfoResponse {
	r.Nickname = v
	return r
}

// GetSex
// 性别，`male` 或 `female` 或 `unknown`
func (r *GetStrangerInfoResponse) GetSex() SexType {
	if r == nil {
		var zero SexType
		return zero
	}
	return r.Sex
}

// SetSex
// 性别，`male` 或 `female` 或 `unknown`
func (r *GetStrangerInfoResponse) SetSex(v SexType) *GetStrangerInfoResponse {
	r.Sex = v
	return r
}

// GetAge
// 年龄
func (r *GetStrangerInfoResponse) GetAge() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Age
}

// SetAge
// 年龄
func (r *GetStrangerInfoResponse) SetAge(v int64) *GetStrangerInfoResponse {
	r.Age = v
	return r
}

// GetUserId
// QQ 号
func (r *GetFriendListResponseItem) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// QQ 号
func (r *GetFriendListResponseItem) SetUserId(v int64) *GetFriendListResponseItem {
	r.UserId = v
	return r
}

// GetNickname
// 昵称
func (r *GetFriendListResponseItem) GetNickname() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Nickname
}

// SetNickname
// 昵称
func (r *GetFriendListResponseItem) SetNickname(v string) *GetFriendListResponseItem {
	r.Nickname = v
	return r
}

// GetRemark
// 备注名
func (r *GetFriendListResponseItem) GetRemark() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Remark
}

// SetRemark
// 备注名
func (r *GetFriendListResponseItem) SetRemark(v string) *GetFriendListResponseItem {
	r.Remark = v
	return r
}

// GetGroupId
// 群号
func (r *GetGroupInfoRequest) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GetGroupInfoRequest) SetGroupId(v int64) *GetGroupInfoRequest {
	r.GroupId = v
	return r
}

// GetNoCache
// 是否不使用缓存（使用缓存可能更新不及时，但响应更快） | 可能的值: false
func (r *GetGroupInfoRequest) GetNoCache() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.NoCache
}

// SetNoCache
// 是否不使用缓存（使用缓存可能更新不及时，但响应更快） | 可能的值: false
func (r *GetGroupInfoRequest) SetNoCache(v bool) *GetGroupInfoRequest {
	r.NoCache = v
	return r
}

// GetGroupId
// 群号
func (r *GetGroupInfoResponse) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GetGroupInfoResponse) SetGroupId(v int64) *GetGroupInfoResponse {
	r.GroupId = v
	return r
}

// GetGroupName
// 群名称
func (r *GetGroupInfoResponse) GetGroupName() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.GroupName
}

// SetGroupName
// 群名称
func (r *GetGroupInfoResponse) SetGroupName(v string) *GetGroupInfoResponse {
	r.GroupName = v
	return r
}

// GetMemberCount
// 成员数
func (r *GetGroupInfoResponse) GetMemberCount() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.MemberCount
}

// SetMemberCount
// 成员数
func (r *GetGroupInfoResponse) SetMemberCount(v int64) *GetGroupInfoResponse {
	r.MemberCount = v
	return r
}

// GetMaxMemberCount
// 最大成员数（群容量）
func (r *GetGroupInfoResponse) GetMaxMemberCount() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.MaxMemberCount
}

// SetMaxMemberCount
// 最大成员数（群容量）
func (r *GetGroupInfoResponse) SetMaxMemberCount(v int64) *GetGroupInfoResponse {
	r.MaxMemberCount = v
	return r
}

// GetGroupId
// 群号
func (r *GetGroupMemberInfoRequest) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GetGroupMemberInfoRequest) SetGroupId(v int64) *GetGroupMemberInfoRequest {
	r.GroupId = v
	return r
}

// GetUserId
// QQ 号
func (r *GetGroupMemberInfoRequest) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// QQ 号
func (r *GetGroupMemberInfoRequest) SetUserId(v int64) *GetGroupMemberInfoRequest {
	r.UserId = v
	return r
}

// GetNoCache
// 是否不使用缓存（使用缓存可能更新不及时，但响应更快） | 可能的值: false
func (r *GetGroupMemberInfoRequest) GetNoCache() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.NoCache
}

// SetNoCache
// 是否不使用缓存（使用缓存可能更新不及时，但响应更快） | 可能的值: false
func (r *GetGroupMemberInfoRequest) SetNoCache(v bool) *GetGroupMemberInfoRequest {
	r.NoCache = v
	return r
}

// GetGroupId
// 群号
func (r *GetGroupMemberInfoResponse) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GetGroupMemberInfoResponse) SetGroupId(v int64) *GetGroupMemberInfoResponse {
	r.GroupId = v
	return r
}

// GetUserId
// QQ 号
func (r *GetGroupMemberInfoResponse) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// QQ 号
func (r *GetGroupMemberInfoResponse) SetUserId(v int64) *GetGroupMemberInfoResponse {
	r.UserId = v
	return r
}

// GetNickname
// 昵称
func (r *GetGroupMemberInfoResponse) GetNickname() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Nickname
}

// SetNickname
// 昵称
func (r *GetGroupMemberInfoResponse) SetNickname(v string) *GetGroupMemberInfoResponse {
	r.Nickname = v
	return r
}

// GetCard
// 群名片／备注
func (r *GetGroupMemberInfoResponse) GetCard() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Card
}

// SetCard
// 群名片／备注
func (r *GetGroupMemberInfoResponse) SetCard(v string) *GetGroupMemberInfoResponse {
	r.Card = v
	return r
}

// GetSex
// 性别，`male` 或 `female` 或 `unknown`
func (r *GetGroupMemberInfoResponse) GetSex() SexType {
	if r == nil {
		var zero SexType
		return zero
	}
	return r.Sex
}

// SetSex
// 性别，`male` 或 `female` 或 `unknown`
func (r *GetGroupMemberInfoResponse) SetSex(v SexType) *GetGroupMemberInfoResponse {
	r.Sex = v
	return r
}

// GetAge
// 年龄
func (r *GetGroupMemberInfoResponse) GetAge() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Age
}

// SetAge
// 年龄
func (r *GetGroupMemberInfoResponse) SetAge(v int64) *GetGroupMemberInfoResponse {
	r.Age = v
	return r
}

// GetArea
// 地区
func (r *GetGroupMemberInfoResponse) GetArea() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Area
}

// SetArea
// 地区
func (r *GetGroupMemberInfoResponse) SetArea(v string) *GetGroupMemberInfoResponse {
	r.Area = v
	return r
}

// GetJoinTime
// 加群时间戳
func (r *GetGroupMemberInfoResponse) GetJoinTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.JoinTime
}

// SetJoinTime
// 加群时间戳
func (r *GetGroupMemberInfoResponse) SetJoinTime(v int64) *GetGroupMemberInfoResponse {
	r.JoinTime = v
	return r
}

// GetLastSentTime
// 最后发言时间戳
func (r *GetGroupMemberInfoResponse) GetLastSentTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.LastSentTime
}

// SetLastSentTime
// 最后发言时间戳
func (r *GetGroupMemberInfoResponse) SetLastSentTime(v int64) *GetGroupMemberInfoResponse {
	r.LastSentTime = v
	return r
}

// GetLevel
// 成员等级
func (r *GetGroupMemberInfoResponse) GetLevel() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Level
}

// SetLevel
// 成员等级
func (r *GetGroupMemberInfoResponse) SetLevel(v string) *GetGroupMemberInfoResponse {
	r.Level = v
	return r
}

// GetRole
// 角色，`owner` 或 `admin` 或 `member`
func (r *GetGroupMemberInfoResponse) GetRole() GroupMemberRoleType {
	if r == nil {
		var zero GroupMemberRoleType
		return zero
	}
	return r.Role
}

// SetRole
// 角色，`owner` 或 `admin` 或 `member`
func (r *GetGroupMemberInfoResponse) SetRole(v GroupMemberRoleType) *GetGroupMemberInfoResponse {
	r.Role = v
	return r
}

// GetUnfriendly
// 是否不良记录成员
func (r *GetGroupMemberInfoResponse) GetUnfriendly() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.Unfriendly
}

// SetUnfriendly
// 是否不良记录成员
func (r *GetGroupMemberInfoResponse) SetUnfriendly(v bool) *GetGroupMemberInfoResponse {
	r.Unfriendly = v
	return r
}

// GetTitle
// 专属头衔
func (r *GetGroupMemberInfoResponse) GetTitle() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Title
}

// SetTitle
// 专属头衔
func (r *GetGroupMemberInfoResponse) SetTitle(v string) *GetGroupMemberInfoResponse {
	r.Title = v
	return r
}

// GetTitleExpireTime
// 专属头衔过期时间戳
func (r *GetGroupMemberInfoResponse) GetTitleExpireTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.TitleExpireTime
}

// SetTitleExpireTime
// 专属头衔过期时间戳
func (r *GetGroupMemberInfoResponse) SetTitleExpireTime(v int64) *GetGroupMemberInfoResponse {
	r.TitleExpireTime = v
	return r
}

// GetCardChangeable
// 是否允许修改群名片
func (r *GetGroupMemberInfoResponse) GetCardChangeable() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.CardChangeable
}

// SetCardChangeable
// 是否允许修改群名片
func (r *GetGroupMemberInfoResponse) SetCardChangeable(v bool) *GetGroupMemberInfoResponse {
	r.CardChangeable = v
	return r
}

// GetGroupId
// 群号
func (r *GetGroupMemberListRequest) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GetGroupMemberListRequest) SetGroupId(v int64) *GetGroupMemberListRequest {
	r.GroupId = v
	return r
}

// GetGroupId
// 群号
func (r *GetGroupHonorInfoRequest) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GetGroupHonorInfoRequest) SetGroupId(v int64) *GetGroupHonorInfoRequest {
	r.GroupId = v
	return r
}

// GetType
// 要获取的群荣誉类型，可传入 `talkative` `performer` `legend` `strong_newbie` `emotion` 以分别获取单个类型的群荣誉数据，或传入 `all` 获取所有数据
func (r *GetGroupHonorInfoRequest) GetType() GroupHonorType {
	if r == nil {
		var zero GroupHonorType
		return zero
	}
	return r.Type
}

// SetType
// 要获取的群荣誉类型，可传入 `talkative` `performer` `legend` `strong_newbie` `emotion` 以分别获取单个类型的群荣誉数据，或传入 `all` 获取所有数据
func (r *GetGroupHonorInfoRequest) SetType(v GroupHonorType) *GetGroupHonorInfoRequest {
	r.Type = v
	return r
}

// GetGroupId
// 群号
func (r *GetGroupHonorInfoResponse) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GetGroupHonorInfoResponse) SetGroupId(v int64) *GetGroupHonorInfoResponse {
	r.GroupId = v
	return r
}

// GetCurrentTalkative
// 当前龙王，仅 `type` 为 `talkative` 或 `all` 时有数据
func (r *GetGroupHonorInfoResponse) GetCurrentTalkative() *GroupHonorInfoCurrentTalkative {
	if r == nil {
		var zero *GroupHonorInfoCurrentTalkative
		return zero
	}
	return r.CurrentTalkative
}

// SetCurrentTalkative
// 当前龙王，仅 `type` 为 `talkative` 或 `all` 时有数据
func (r *GetGroupHonorInfoResponse) SetCurrentTalkative(v *GroupHonorInfoCurrentTalkative) *GetGroupHonorInfoResponse {
	r.CurrentTalkative = v
	return r
}

// GetTalkativeList
// 历史龙王，仅 `type` 为 `talkative` 或 `all` 时有数据
func (r *GetGroupHonorInfoResponse) GetTalkativeList() []*GroupHonorInfoListItem {
	if r == nil {
		var zero []*GroupHonorInfoListItem
		return zero
	}
	return r.TalkativeList
}

// SetTalkativeList
// 历史龙王，仅 `type` 为 `talkative` 或 `all` 时有数据
func (r *GetGroupHonorInfoResponse) SetTalkativeList(v []*GroupHonorInfoListItem) *GetGroupHonorInfoResponse {
	r.TalkativeList = v
	return r
}

// GetPerformerList
// 群聊之火，仅 `type` 为 `performer` 或 `all` 时有数据
func (r *GetGroupHonorInfoResponse) GetPerformerList() []*GroupHonorInfoListItem {
	if r == nil {
		var zero []*GroupHonorInfoListItem
		return zero
	}
	return r.PerformerList
}

// SetPerformerList
// 群聊之火，仅 `type` 为 `performer` 或 `all` 时有数据
func (r *GetGroupHonorInfoResponse) SetPerformerList(v []*GroupHonorInfoListItem) *GetGroupHonorInfoResponse {
	r.PerformerList = v
	return r
}

// GetLegendList
// 群聊炽焰，仅 `type` 为 `legend` 或 `all` 时有数据
func (r *GetGroupHonorInfoResponse) GetLegendList() []*GroupHonorInfoListItem {
	if r == nil {
		var zero []*GroupHonorInfoListItem
		return zero
	}
	return r.LegendList
}

// SetLegendList
// 群聊炽焰，仅 `type` 为 `legend` 或 `all` 时有数据
func (r *GetGroupHonorInfoResponse) SetLegendList(v []*GroupHonorInfoListItem) *GetGroupHonorInfoResponse {
	r.LegendList = v
	return r
}

// GetStrongNewbieList
// 冒尖小春笋，仅 `type` 为 `strong_newbie` 或 `all` 时有数据
func (r *GetGroupHonorInfoResponse) GetStrongNewbieList() []*GroupHonorInfoListItem {
	if r == nil {
		var zero []*GroupHonorInfoListItem
		return zero
	}
	return r.StrongNewbieList
}

// SetStrongNewbieList
// 冒尖小春笋，仅 `type` 为 `strong_newbie` 或 `all` 时有数据
func (r *GetGroupHonorInfoResponse) SetStrongNewbieList(v []*GroupHonorInfoListItem) *GetGroupHonorInfoResponse {
	r.StrongNewbieList = v
	return r
}

// GetEmotionList
// 快乐之源，仅 `type` 为 `emotion` 或 `all` 时有数据
func (r *GetGroupHonorInfoResponse) GetEmotionList() []*GroupHonorInfoListItem {
	if r == nil {
		var zero []*GroupHonorInfoListItem
		return zero
	}
	return r.EmotionList
}

// SetEmotionList
// 快乐之源，仅 `type` 为 `emotion` 或 `all` 时有数据
func (r *GetGroupHonorInfoResponse) SetEmotionList(v []*GroupHonorInfoListItem) *GetGroupHonorInfoResponse {
	r.EmotionList = v
	return r
}

// GetUserId
// QQ 号
func (r *GroupHonorInfoCurrentTalkative) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// QQ 号
func (r *GroupHonorInfoCurrentTalkative) SetUserId(v int64) *GroupHonorInfoCurrentTalkative {
	r.UserId = v
	return r
}

// GetNickname
// 昵称
func (r *GroupHonorInfoCurrentTalkative) GetNickname() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Nickname
}

// SetNickname
// 昵称
func (r *GroupHonorInfoCurrentTalkative) SetNickname(v string) *GroupHonorInfoCurrentTalkative {
	r.Nickname = v
	return r
}

// GetAvatar
// 头像 URL
func (r *GroupHonorInfoCurrentTalkative) GetAvatar() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Avatar
}

// SetAvatar
// 头像 URL
func (r *GroupHonorInfoCurrentTalkative) SetAvatar(v string) *GroupHonorInfoCurrentTalkative {
	r.Avatar = v
	return r
}

// GetDayCount
// 持续天数
func (r *GroupHonorInfoCurrentTalkative) GetDayCount() int32 {
	if r == nil {
		var zero int32
		return zero
	}
	return r.DayCount
}

// SetDayCount
// 持续天数
func (r *GroupHonorInfoCurrentTalkative) SetDayCount(v int32) *GroupHonorInfoCurrentTalkative {
	r.DayCount = v
	return r
}

// GetUserId
// QQ 号
func (r *GroupHonorInfoListItem) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// QQ 号
func (r *GroupHonorInfoListItem) SetUserId(v int64) *GroupHonorInfoListItem {
	r.UserId = v
	return r
}

// GetNickname
// 昵称
func (r *GroupHonorInfoListItem) GetNickname() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Nickname
}

// SetNickname
// 昵称
func (r *GroupHonorInfoListItem) SetNickname(v string) *GroupHonorInfoListItem {
	r.Nickname = v
	return r
}

// GetAvatar
// 头像 URL
func (r *GroupHonorInfoListItem) GetAvatar() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Avatar
}

// SetAvatar
// 头像 URL
func (r *GroupHonorInfoListItem) SetAvatar(v string) *GroupHonorInfoListItem {
	r.Avatar = v
	return r
}

// GetDescription
// 荣誉描述
func (r *GroupHonorInfoListItem) GetDescription() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Description
}

// SetDescription
// 荣誉描述
func (r *GroupHonorInfoListItem) SetDescription(v string) *GroupHonorInfoListItem {
	r.Description = v
	return r
}

// GetDomain
// 需要获取 cookies 的域名 | 默认值: 空
func (r *GetCookiesRequest) GetDomain() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Domain
}

// SetDomain
// 需要获取 cookies 的域名 | 默认值: 空
func (r *GetCookiesRequest) SetDomain(v string) *GetCookiesRequest {
	r.Domain = v
	return r
}

// GetCookies
// Cookies
func (r *GetCookiesResponse) GetCookies() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Cookies
}

// SetCookies
// Cookies
func (r *GetCookiesResponse) SetCookies(v string) *GetCookiesResponse {
	r.Cookies = v
	return r
}

// GetToken
// CSRF Token
func (r *GetCsrfTokenResponse) GetToken() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Token
}

// SetToken
// CSRF Token
func (r *GetCsrfTokenResponse) SetToken(v int64) *GetCsrfTokenResponse {
	r.Token = v
	return r
}

// GetDomain
// 需要获取 cookies 的域名 | 默认值: 空
func (r *GetCredentialsRequest) GetDomain() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Domain
}

// SetDomain
// 需要获取 cookies 的域名 | 默认值: 空
func (r *GetCredentialsRequest) SetDomain(v string) *GetCredentialsRequest {
	r.Domain = v
	return r
}

// GetCookies
// Cookies
func (r *GetCredentialsResponse) GetCookies() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Cookies
}

// SetCookies
// Cookies
func (r *GetCredentialsResponse) SetCookies(v string) *GetCredentialsResponse {
	r.Cookies = v
	return r
}

// GetCsrfToken
// CSRF Token
func (r *GetCredentialsResponse) GetCsrfToken() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.CsrfToken
}

// SetCsrfToken
// CSRF Token
func (r *GetCredentialsResponse) SetCsrfToken(v int64) *GetCredentialsResponse {
	r.CsrfToken = v
	return r
}

// GetFile
// 收到的语音文件名（消息段的 `file` 参数），如 `0B38145AA44505000B38145AA4450500.silk`
func (r *GetRecordRequest) GetFile() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.File
}

// SetFile
// 收到的语音文件名（消息段的 `file` 参数），如 `0B38145AA44505000B38145AA4450500.silk`
func (r *GetRecordRequest) SetFile(v string) *GetRecordRequest {
	r.File = v
	return r
}

// GetOutFormat
// 要转换到的格式，目前支持 `mp3`、`amr`、`wma`、`m4a`、`spx`、`ogg`、`wav`、`flac`
func (r *GetRecordRequest) GetOutFormat() GetRecordOutputFormat {
	if r == nil {
		var zero GetRecordOutputFormat
		return zero
	}
	return r.OutFormat
}

// SetOutFormat
// 要转换到的格式，目前支持 `mp3`、`amr`、`wma`、`m4a`、`spx`、`ogg`、`wav`、`flac`
func (r *GetRecordRequest) SetOutFormat(v GetRecordOutputFormat) *GetRecordRequest {
	r.OutFormat = v
	return r
}

// GetFile
// 转换后的语音文件路径，如 `/home/somebody/cqhttp/data/record/0B38145AA44505000B38145AA4450500.mp3`
func (r *GetRecordResponse) GetFile() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.File
}

// SetFile
// 转换后的语音文件路径，如 `/home/somebody/cqhttp/data/record/0B38145AA44505000B38145AA4450500.mp3`
func (r *GetRecordResponse) SetFile(v string) *GetRecordResponse {
	r.File = v
	return r
}

// GetFile
// 收到的图片文件名（消息段的 `file` 参数），如 `6B4DE3DFD1BD271E3297859D41C530F5.jpg`
func (r *GetImageRequest) GetFile() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.File
}

// SetFile
// 收到的图片文件名（消息段的 `file` 参数），如 `6B4DE3DFD1BD271E3297859D41C530F5.jpg`
func (r *GetImageRequest) SetFile(v string) *GetImageRequest {
	r.File = v
	return r
}

// GetFile
// 下载后的图片文件路径，如 `/home/somebody/cqhttp/data/image/6B4DE3DFD1BD271E3297859D41C530F5.jpg`
func (r *GetImageResponse) GetFile() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.File
}

// SetFile
// 下载后的图片文件路径，如 `/home/somebody/cqhttp/data/image/6B4DE3DFD1BD271E3297859D41C530F5.jpg`
func (r *GetImageResponse) SetFile(v string) *GetImageResponse {
	r.File = v
	return r
}

// GetYes
// 是或否
func (r *CanSendImageResponse) GetYes() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.Yes
}

// SetYes
// 是或否
func (r *CanSendImageResponse) SetYes(v bool) *CanSendImageResponse {
	r.Yes = v
	return r
}

// GetYes
// 是或否
func (r *CanSendRecordResponse) GetYes() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.Yes
}

// SetYes
// 是或否
func (r *CanSendRecordResponse) SetYes(v bool) *CanSendRecordResponse {
	r.Yes = v
	return r
}

// GetAppName
// 应用标识，如 `mirai-native`
func (r *GetVersionInfoResponse) GetAppName() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.AppName
}

// SetAppName
// 应用标识，如 `mirai-native`
func (r *GetVersionInfoResponse) SetAppName(v string) *GetVersionInfoResponse {
	r.AppName = v
	return r
}

// GetAppVersion
// 应用版本，如 `1.2.3`
func (r *GetVersionInfoResponse) GetAppVersion() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.AppVersion
}

// SetAppVersion
// 应用版本，如 `1.2.3`
func (r *GetVersionInfoResponse) SetAppVersion(v string) *GetVersionInfoResponse {
	r.AppVersion = v
	return r
}

// GetProtocolVersion
// OneBot 标准版本，如 `v11`
func (r *GetVersionInfoResponse) GetProtocolVersion() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.ProtocolVersion
}

// SetProtocolVersion
// OneBot 标准版本，如 `v11`
func (r *GetVersionInfoResponse) SetProtocolVersion(v string) *GetVersionInfoResponse {
	r.ProtocolVersion = v
	return r
}

// GetDelay
// 要延迟的毫秒数，如果默认情况下无法重启，可以尝试设置延迟为 2000 左右 | 可能的值: 0
func (r *SetRestartRequest) GetDelay() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Delay
}

// SetDelay
// 要延迟的毫秒数，如果默认情况下无法重启，可以尝试设置延迟为 2000 左右 | 可能的值: 0
func (r *SetRestartRequest) SetDelay(v int64) *SetRestartRequest {
	r.Delay = v
	return r
}
