// Code generated by entity-gen. DO NOT EDIT.

package entity

// GetOnline
// 当前 QQ 在线，`null` 表示无法查询到在线状态
func (r *StatusMeta) GetOnline() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.Online
}

// SetOnline
// 当前 QQ 在线，`null` 表示无法查询到在线状态
func (r *StatusMeta) SetOnline(v bool) *StatusMeta {
	r.Online = v
	return r
}

// GetGood
// 状态符合预期，意味着各模块正常运行、功能正常，且 QQ 在线
func (r *StatusMeta) GetGood() bool {
	if r == nil {
		var zero bool
		return zero
	}
	return r.Good
}

// SetGood
// 状态符合预期，意味着各模块正常运行、功能正常，且 QQ 在线
func (r *StatusMeta) SetGood(v bool) *StatusMeta {
	r.Good = v
	return r
}

// GetId
// 匿名用户 ID
func (r *GroupAnonymousUser) GetId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Id
}

// SetId
// 匿名用户 ID
func (r *GroupAnonymousUser) SetId(v int64) *GroupAnonymousUser {
	r.Id = v
	return r
}

// GetName
// 匿名用户名称
func (r *GroupAnonymousUser) GetName() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Name
}

// SetName
// 匿名用户名称
func (r *GroupAnonymousUser) SetName(v string) *GroupAnonymousUser {
	r.Name = v
	return r
}

// GetFlag
// 匿名用户 flag，在调用禁言 API 时需要传入
func (r *GroupAnonymousUser) GetFlag() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Flag
}

// SetFlag
// 匿名用户 flag，在调用禁言 API 时需要传入
func (r *GroupAnonymousUser) SetFlag(v string) *GroupAnonymousUser {
	r.Flag = v
	return r
}
