// Code generated by entity-gen. DO NOT EDIT.

package entity

import (
	"encoding/json"
)

// GetAction
// Action 为路径段，例如 send_private_msg
func (r *ActionRequest) GetAction() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Action
}

// SetAction
// Action 为路径段，例如 send_private_msg
func (r *ActionRequest) SetAction(v string) *ActionRequest {
	r.Action = v
	return r
}

// GetParams
// Params 保存解析后的参数映射，可能来自 query/form/JSON
func (r *ActionRequest) GetParams() map[string]any {
	if r == nil {
		var zero map[string]any
		return zero
	}
	return r.Params
}

// SetParams
// Params 保存解析后的参数映射，可能来自 query/form/JSON
func (r *ActionRequest) SetParams(v map[string]any) *ActionRequest {
	r.Params = v
	return r
}

// GetStatus
// ok | async | failed
func (r *ActionRawResponse) GetStatus() ActionResponseStatus {
	if r == nil {
		var zero ActionResponseStatus
		return zero
	}
	return r.Status
}

// SetStatus
// ok | async | failed
func (r *ActionRawResponse) SetStatus(v ActionResponseStatus) *ActionRawResponse {
	r.Status = v
	return r
}

// GetRetcode
// 0=成功,1=异步,其他=失败
func (r *ActionRawResponse) GetRetcode() ActionResponseRetcode {
	if r == nil {
		var zero ActionResponseRetcode
		return zero
	}
	return r.Retcode
}

// SetRetcode
// 0=成功,1=异步,其他=失败
func (r *ActionRawResponse) SetRetcode(v ActionResponseRetcode) *ActionRawResponse {
	r.Retcode = v
	return r
}

// GetData
// 返回数据，可能为 null
func (r *ActionRawResponse) GetData() json.RawMessage {
	if r == nil {
		var zero json.RawMessage
		return zero
	}
	return r.Data
}

// SetData
// 返回数据，可能为 null
func (r *ActionRawResponse) SetData(v json.RawMessage) *ActionRawResponse {
	r.Data = v
	return r
}

// GetMessage
// 可选，人类可读的错误信息
func (r *ActionRawResponse) GetMessage() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Message
}

// SetMessage
// 可选，人类可读的错误信息
func (r *ActionRawResponse) SetMessage(v string) *ActionRawResponse {
	r.Message = v
	return r
}

func (r *ActionRequestEnvelope) GetActionRequest() ActionRequest {
	if r == nil {
		var zero ActionRequest
		return zero
	}
	return r.ActionRequest
}

func (r *ActionRequestEnvelope) SetActionRequest(v ActionRequest) *ActionRequestEnvelope {
	r.ActionRequest = v
	return r
}

func (r *ActionRequestEnvelope) GetEcho() json.RawMessage {
	if r == nil {
		var zero json.RawMessage
		return zero
	}
	return r.Echo
}

func (r *ActionRequestEnvelope) SetEcho(v json.RawMessage) *ActionRequestEnvelope {
	r.Echo = v
	return r
}

func (r *ActionResponseEnvelope) GetActionRawResponse() ActionRawResponse {
	if r == nil {
		var zero ActionRawResponse
		return zero
	}
	return r.ActionRawResponse
}

func (r *ActionResponseEnvelope) SetActionRawResponse(v ActionRawResponse) *ActionResponseEnvelope {
	r.ActionRawResponse = v
	return r
}

func (r *ActionResponseEnvelope) GetEcho() json.RawMessage {
	if r == nil {
		var zero json.RawMessage
		return zero
	}
	return r.Echo
}

func (r *ActionResponseEnvelope) SetEcho(v json.RawMessage) *ActionResponseEnvelope {
	r.Echo = v
	return r
}

// GetStatus
// ok | async | failed
func (r *ActionResponse[T]) GetStatus() ActionResponseStatus {
	if r == nil {
		var zero ActionResponseStatus
		return zero
	}
	return r.Status
}

// SetStatus
// ok | async | failed
func (r *ActionResponse[T]) SetStatus(v ActionResponseStatus) *ActionResponse[T] {
	r.Status = v
	return r
}

// GetRetcode
// 0=成功,1=异步,其他=失败
func (r *ActionResponse[T]) GetRetcode() ActionResponseRetcode {
	if r == nil {
		var zero ActionResponseRetcode
		return zero
	}
	return r.Retcode
}

// SetRetcode
// 0=成功,1=异步,其他=失败
func (r *ActionResponse[T]) SetRetcode(v ActionResponseRetcode) *ActionResponse[T] {
	r.Retcode = v
	return r
}

// GetData
// 返回数据，可能为 null
func (r *ActionResponse[T]) GetData() *T {
	if r == nil {
		var zero *T
		return zero
	}
	return r.Data
}

// SetData
// 返回数据，可能为 null
func (r *ActionResponse[T]) SetData(v *T) *ActionResponse[T] {
	r.Data = v
	return r
}

// GetMessage
// 可选，人类可读的错误信息
func (r *ActionResponse[T]) GetMessage() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Message
}

// SetMessage
// 可选，人类可读的错误信息
func (r *ActionResponse[T]) SetMessage(v string) *ActionResponse[T] {
	r.Message = v
	return r
}

func (r *ActionError) GetUrlPath() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.UrlPath
}

func (r *ActionError) SetUrlPath(v string) *ActionError {
	r.UrlPath = v
	return r
}

func (r *ActionError) GetStatus() ActionResponseStatus {
	if r == nil {
		var zero ActionResponseStatus
		return zero
	}
	return r.Status
}

func (r *ActionError) SetStatus(v ActionResponseStatus) *ActionError {
	r.Status = v
	return r
}

func (r *ActionError) GetRetcode() ActionResponseRetcode {
	if r == nil {
		var zero ActionResponseRetcode
		return zero
	}
	return r.Retcode
}

func (r *ActionError) SetRetcode(v ActionResponseRetcode) *ActionError {
	r.Retcode = v
	return r
}

func (r *ActionError) GetMessage() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Message
}

func (r *ActionError) SetMessage(v string) *ActionError {
	r.Message = v
	return r
}
