// Code generated by entity-gen. DO NOT EDIT.

package entity

// GetTime
// 事件发生的时间戳
func (r *PrivateMessageEvent) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 事件发生的时间戳
func (r *PrivateMessageEvent) SetTime(v int64) *PrivateMessageEvent {
	r.Time = v
	return r
}

// GetSelfId
// 收到事件的机器人 QQ 号
func (r *PrivateMessageEvent) GetSelfId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.SelfId
}

// SetSelfId
// 收到事件的机器人 QQ 号
func (r *PrivateMessageEvent) SetSelfId(v int64) *PrivateMessageEvent {
	r.SelfId = v
	return r
}

// GetPostType
// 上报类型 | 可能的值: message
func (r *PrivateMessageEvent) GetPostType() EventPostType {
	if r == nil {
		var zero EventPostType
		return zero
	}
	return r.PostType
}

// SetPostType
// 上报类型 | 可能的值: message
func (r *PrivateMessageEvent) SetPostType(v EventPostType) *PrivateMessageEvent {
	r.PostType = v
	return r
}

// GetMessageType
// 消息类型 | 可能的值: private
func (r *PrivateMessageEvent) GetMessageType() EventMessageType {
	if r == nil {
		var zero EventMessageType
		return zero
	}
	return r.MessageType
}

// SetMessageType
// 消息类型 | 可能的值: private
func (r *PrivateMessageEvent) SetMessageType(v EventMessageType) *PrivateMessageEvent {
	r.MessageType = v
	return r
}

// GetSubType
// 消息子类型，如果是好友则是 `friend`，如果是群临时会话则是 `group` | 可能的值: friend, group, other
func (r *PrivateMessageEvent) GetSubType() EventPrivateMessageSubType {
	if r == nil {
		var zero EventPrivateMessageSubType
		return zero
	}
	return r.SubType
}

// SetSubType
// 消息子类型，如果是好友则是 `friend`，如果是群临时会话则是 `group` | 可能的值: friend, group, other
func (r *PrivateMessageEvent) SetSubType(v EventPrivateMessageSubType) *PrivateMessageEvent {
	r.SubType = v
	return r
}

// GetMessageId
// 消息 ID
func (r *PrivateMessageEvent) GetMessageId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.MessageId
}

// SetMessageId
// 消息 ID
func (r *PrivateMessageEvent) SetMessageId(v int64) *PrivateMessageEvent {
	r.MessageId = v
	return r
}

// GetUserId
// 发送者 QQ 号
func (r *PrivateMessageEvent) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 发送者 QQ 号
func (r *PrivateMessageEvent) SetUserId(v int64) *PrivateMessageEvent {
	r.UserId = v
	return r
}

// GetMessage
// 消息内容
// 可以是字符串 (CQ 码格式) 或消息段数组
func (r *PrivateMessageEvent) GetMessage() *MessageValue {
	if r == nil {
		var zero *MessageValue
		return zero
	}
	return r.Message
}

// SetMessage
// 消息内容
// 可以是字符串 (CQ 码格式) 或消息段数组
func (r *PrivateMessageEvent) SetMessage(v *MessageValue) *PrivateMessageEvent {
	r.Message = v
	return r
}

// GetRawMessage
// 原始消息内容
func (r *PrivateMessageEvent) GetRawMessage() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.RawMessage
}

// SetRawMessage
// 原始消息内容
func (r *PrivateMessageEvent) SetRawMessage(v string) *PrivateMessageEvent {
	r.RawMessage = v
	return r
}

// GetFont
// 字体
func (r *PrivateMessageEvent) GetFont() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Font
}

// SetFont
// 字体
func (r *PrivateMessageEvent) SetFont(v int64) *PrivateMessageEvent {
	r.Font = v
	return r
}

// GetSender
// 发送人信息
func (r *PrivateMessageEvent) GetSender() *PrivateMessageEventSender {
	if r == nil {
		var zero *PrivateMessageEventSender
		return zero
	}
	return r.Sender
}

// SetSender
// 发送人信息
func (r *PrivateMessageEvent) SetSender(v *PrivateMessageEventSender) *PrivateMessageEvent {
	r.Sender = v
	return r
}

// GetUserId
// QQ 号
func (r *PrivateMessageEventSender) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// QQ 号
func (r *PrivateMessageEventSender) SetUserId(v int64) *PrivateMessageEventSender {
	r.UserId = v
	return r
}

// GetNickname
// 昵称
func (r *PrivateMessageEventSender) GetNickname() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Nickname
}

// SetNickname
// 昵称
func (r *PrivateMessageEventSender) SetNickname(v string) *PrivateMessageEventSender {
	r.Nickname = v
	return r
}

// GetSex
// 性别，`male` 或 `female` 或 `unknown`
func (r *PrivateMessageEventSender) GetSex() SexType {
	if r == nil {
		var zero SexType
		return zero
	}
	return r.Sex
}

// SetSex
// 性别，`male` 或 `female` 或 `unknown`
func (r *PrivateMessageEventSender) SetSex(v SexType) *PrivateMessageEventSender {
	r.Sex = v
	return r
}

// GetAge
// 年龄
func (r *PrivateMessageEventSender) GetAge() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Age
}

// SetAge
// 年龄
func (r *PrivateMessageEventSender) SetAge(v int64) *PrivateMessageEventSender {
	r.Age = v
	return r
}

// GetTime
// 事件发生的时间戳
func (r *GroupMessageEvent) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 事件发生的时间戳
func (r *GroupMessageEvent) SetTime(v int64) *GroupMessageEvent {
	r.Time = v
	return r
}

// GetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupMessageEvent) GetSelfId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.SelfId
}

// SetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupMessageEvent) SetSelfId(v int64) *GroupMessageEvent {
	r.SelfId = v
	return r
}

// GetPostType
// 上报类型 | 可能的值: message
func (r *GroupMessageEvent) GetPostType() EventPostType {
	if r == nil {
		var zero EventPostType
		return zero
	}
	return r.PostType
}

// SetPostType
// 上报类型 | 可能的值: message
func (r *GroupMessageEvent) SetPostType(v EventPostType) *GroupMessageEvent {
	r.PostType = v
	return r
}

// GetMessageType
// 消息类型 | 可能的值: group
func (r *GroupMessageEvent) GetMessageType() EventMessageType {
	if r == nil {
		var zero EventMessageType
		return zero
	}
	return r.MessageType
}

// SetMessageType
// 消息类型 | 可能的值: group
func (r *GroupMessageEvent) SetMessageType(v EventMessageType) *GroupMessageEvent {
	r.MessageType = v
	return r
}

// GetSubType
// 消息子类型，正常消息是 `normal`，匿名消息是 `anonymous`，系统提示（如「管理员已禁止群内匿名聊天」）是 `notice` | 可能的值: normal, anonymous, notice
func (r *GroupMessageEvent) GetSubType() EventGroupMessageSubType {
	if r == nil {
		var zero EventGroupMessageSubType
		return zero
	}
	return r.SubType
}

// SetSubType
// 消息子类型，正常消息是 `normal`，匿名消息是 `anonymous`，系统提示（如「管理员已禁止群内匿名聊天」）是 `notice` | 可能的值: normal, anonymous, notice
func (r *GroupMessageEvent) SetSubType(v EventGroupMessageSubType) *GroupMessageEvent {
	r.SubType = v
	return r
}

// GetMessageId
// 消息 ID
func (r *GroupMessageEvent) GetMessageId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.MessageId
}

// SetMessageId
// 消息 ID
func (r *GroupMessageEvent) SetMessageId(v int64) *GroupMessageEvent {
	r.MessageId = v
	return r
}

// GetGroupId
// 群号
func (r *GroupMessageEvent) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GroupMessageEvent) SetGroupId(v int64) *GroupMessageEvent {
	r.GroupId = v
	return r
}

// GetUserId
// 发送者 QQ 号
func (r *GroupMessageEvent) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 发送者 QQ 号
func (r *GroupMessageEvent) SetUserId(v int64) *GroupMessageEvent {
	r.UserId = v
	return r
}

// GetAnonymous
// 匿名信息，如果不是匿名消息则为 null
func (r *GroupMessageEvent) GetAnonymous() *GroupAnonymousUser {
	if r == nil {
		var zero *GroupAnonymousUser
		return zero
	}
	return r.Anonymous
}

// SetAnonymous
// 匿名信息，如果不是匿名消息则为 null
func (r *GroupMessageEvent) SetAnonymous(v *GroupAnonymousUser) *GroupMessageEvent {
	r.Anonymous = v
	return r
}

// GetMessage
// 消息内容
// 可以是字符串 (CQ 码格式) 或消息段数组
func (r *GroupMessageEvent) GetMessage() *MessageValue {
	if r == nil {
		var zero *MessageValue
		return zero
	}
	return r.Message
}

// SetMessage
// 消息内容
// 可以是字符串 (CQ 码格式) 或消息段数组
func (r *GroupMessageEvent) SetMessage(v *MessageValue) *GroupMessageEvent {
	r.Message = v
	return r
}

// GetRawMessage
// 原始消息内容
func (r *GroupMessageEvent) GetRawMessage() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.RawMessage
}

// SetRawMessage
// 原始消息内容
func (r *GroupMessageEvent) SetRawMessage(v string) *GroupMessageEvent {
	r.RawMessage = v
	return r
}

// GetFont
// 字体
func (r *GroupMessageEvent) GetFont() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Font
}

// SetFont
// 字体
func (r *GroupMessageEvent) SetFont(v int64) *GroupMessageEvent {
	r.Font = v
	return r
}

// GetSender
// 发送人信息
func (r *GroupMessageEvent) GetSender() *GroupMessageEventSender {
	if r == nil {
		var zero *GroupMessageEventSender
		return zero
	}
	return r.Sender
}

// SetSender
// 发送人信息
func (r *GroupMessageEvent) SetSender(v *GroupMessageEventSender) *GroupMessageEvent {
	r.Sender = v
	return r
}

// GetUserId
// 发送者 QQ 号
func (r *GroupMessageEventSender) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 发送者 QQ 号
func (r *GroupMessageEventSender) SetUserId(v int64) *GroupMessageEventSender {
	r.UserId = v
	return r
}

// GetNickname
// 昵称
func (r *GroupMessageEventSender) GetNickname() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Nickname
}

// SetNickname
// 昵称
func (r *GroupMessageEventSender) SetNickname(v string) *GroupMessageEventSender {
	r.Nickname = v
	return r
}

// GetCard
// 群名片／备注
func (r *GroupMessageEventSender) GetCard() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Card
}

// SetCard
// 群名片／备注
func (r *GroupMessageEventSender) SetCard(v string) *GroupMessageEventSender {
	r.Card = v
	return r
}

// GetSex
// 性别，male 或 female 或 unknown
func (r *GroupMessageEventSender) GetSex() SexType {
	if r == nil {
		var zero SexType
		return zero
	}
	return r.Sex
}

// SetSex
// 性别，male 或 female 或 unknown
func (r *GroupMessageEventSender) SetSex(v SexType) *GroupMessageEventSender {
	r.Sex = v
	return r
}

// GetAge
// 年龄
func (r *GroupMessageEventSender) GetAge() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Age
}

// SetAge
// 年龄
func (r *GroupMessageEventSender) SetAge(v int64) *GroupMessageEventSender {
	r.Age = v
	return r
}

// GetArea
// 地区
func (r *GroupMessageEventSender) GetArea() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Area
}

// SetArea
// 地区
func (r *GroupMessageEventSender) SetArea(v string) *GroupMessageEventSender {
	r.Area = v
	return r
}

// GetLevel
// 成员等级
func (r *GroupMessageEventSender) GetLevel() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Level
}

// SetLevel
// 成员等级
func (r *GroupMessageEventSender) SetLevel(v string) *GroupMessageEventSender {
	r.Level = v
	return r
}

// GetRole
// 角色，owner 或 admin 或 member
func (r *GroupMessageEventSender) GetRole() GroupMemberRoleType {
	if r == nil {
		var zero GroupMemberRoleType
		return zero
	}
	return r.Role
}

// SetRole
// 角色，owner 或 admin 或 member
func (r *GroupMessageEventSender) SetRole(v GroupMemberRoleType) *GroupMessageEventSender {
	r.Role = v
	return r
}

// GetTitle
// 专属头衔
func (r *GroupMessageEventSender) GetTitle() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Title
}

// SetTitle
// 专属头衔
func (r *GroupMessageEventSender) SetTitle(v string) *GroupMessageEventSender {
	r.Title = v
	return r
}

// GetTime
// 事件发生的时间戳
func (r *GroupFileUploadEvent) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 事件发生的时间戳
func (r *GroupFileUploadEvent) SetTime(v int64) *GroupFileUploadEvent {
	r.Time = v
	return r
}

// GetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupFileUploadEvent) GetSelfId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.SelfId
}

// SetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupFileUploadEvent) SetSelfId(v int64) *GroupFileUploadEvent {
	r.SelfId = v
	return r
}

// GetPostType
// 上报类型 | 可能的值: notice
func (r *GroupFileUploadEvent) GetPostType() EventPostType {
	if r == nil {
		var zero EventPostType
		return zero
	}
	return r.PostType
}

// SetPostType
// 上报类型 | 可能的值: notice
func (r *GroupFileUploadEvent) SetPostType(v EventPostType) *GroupFileUploadEvent {
	r.PostType = v
	return r
}

// GetNoticeType
// 通知类型 | 可能的值: group_upload
func (r *GroupFileUploadEvent) GetNoticeType() EventNoticeType {
	if r == nil {
		var zero EventNoticeType
		return zero
	}
	return r.NoticeType
}

// SetNoticeType
// 通知类型 | 可能的值: group_upload
func (r *GroupFileUploadEvent) SetNoticeType(v EventNoticeType) *GroupFileUploadEvent {
	r.NoticeType = v
	return r
}

// GetGroupId
// 群号
func (r *GroupFileUploadEvent) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GroupFileUploadEvent) SetGroupId(v int64) *GroupFileUploadEvent {
	r.GroupId = v
	return r
}

// GetUserId
// 发送者 QQ 号
func (r *GroupFileUploadEvent) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 发送者 QQ 号
func (r *GroupFileUploadEvent) SetUserId(v int64) *GroupFileUploadEvent {
	r.UserId = v
	return r
}

// GetFile
// 文件信息
func (r *GroupFileUploadEvent) GetFile() *GroupFileUploadEventFile {
	if r == nil {
		var zero *GroupFileUploadEventFile
		return zero
	}
	return r.File
}

// SetFile
// 文件信息
func (r *GroupFileUploadEvent) SetFile(v *GroupFileUploadEventFile) *GroupFileUploadEvent {
	r.File = v
	return r
}

// GetId
// 文件 ID
func (r *GroupFileUploadEventFile) GetId() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Id
}

// SetId
// 文件 ID
func (r *GroupFileUploadEventFile) SetId(v string) *GroupFileUploadEventFile {
	r.Id = v
	return r
}

// GetName
// 文件名
func (r *GroupFileUploadEventFile) GetName() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Name
}

// SetName
// 文件名
func (r *GroupFileUploadEventFile) SetName(v string) *GroupFileUploadEventFile {
	r.Name = v
	return r
}

// GetSize
// 文件大小（字节数）
func (r *GroupFileUploadEventFile) GetSize() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Size
}

// SetSize
// 文件大小（字节数）
func (r *GroupFileUploadEventFile) SetSize(v int64) *GroupFileUploadEventFile {
	r.Size = v
	return r
}

// GetBusId
// busid（目前不清楚有什么作用）
func (r *GroupFileUploadEventFile) GetBusId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.BusId
}

// SetBusId
// busid（目前不清楚有什么作用）
func (r *GroupFileUploadEventFile) SetBusId(v int64) *GroupFileUploadEventFile {
	r.BusId = v
	return r
}

// GetTime
// 事件发生的时间戳
func (r *GroupAdminChangeEvent) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 事件发生的时间戳
func (r *GroupAdminChangeEvent) SetTime(v int64) *GroupAdminChangeEvent {
	r.Time = v
	return r
}

// GetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupAdminChangeEvent) GetSelfId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.SelfId
}

// SetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupAdminChangeEvent) SetSelfId(v int64) *GroupAdminChangeEvent {
	r.SelfId = v
	return r
}

// GetPostType
// 上报类型 | 可能的值: notice
func (r *GroupAdminChangeEvent) GetPostType() EventPostType {
	if r == nil {
		var zero EventPostType
		return zero
	}
	return r.PostType
}

// SetPostType
// 上报类型 | 可能的值: notice
func (r *GroupAdminChangeEvent) SetPostType(v EventPostType) *GroupAdminChangeEvent {
	r.PostType = v
	return r
}

// GetNoticeType
// 通知类型 | 可能的值: group_admin
func (r *GroupAdminChangeEvent) GetNoticeType() EventNoticeType {
	if r == nil {
		var zero EventNoticeType
		return zero
	}
	return r.NoticeType
}

// SetNoticeType
// 通知类型 | 可能的值: group_admin
func (r *GroupAdminChangeEvent) SetNoticeType(v EventNoticeType) *GroupAdminChangeEvent {
	r.NoticeType = v
	return r
}

// GetSubType
// 事件子类型，分别表示设置和取消管理员 | 可能的值: set, unset
func (r *GroupAdminChangeEvent) GetSubType() EventGroupAdminChangeSubType {
	if r == nil {
		var zero EventGroupAdminChangeSubType
		return zero
	}
	return r.SubType
}

// SetSubType
// 事件子类型，分别表示设置和取消管理员 | 可能的值: set, unset
func (r *GroupAdminChangeEvent) SetSubType(v EventGroupAdminChangeSubType) *GroupAdminChangeEvent {
	r.SubType = v
	return r
}

// GetGroupId
// 群号
func (r *GroupAdminChangeEvent) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GroupAdminChangeEvent) SetGroupId(v int64) *GroupAdminChangeEvent {
	r.GroupId = v
	return r
}

// GetUserId
// 管理员 QQ 号
func (r *GroupAdminChangeEvent) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 管理员 QQ 号
func (r *GroupAdminChangeEvent) SetUserId(v int64) *GroupAdminChangeEvent {
	r.UserId = v
	return r
}

// GetTime
// 事件发生的时间戳
func (r *GroupMemberDecreaseEvent) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 事件发生的时间戳
func (r *GroupMemberDecreaseEvent) SetTime(v int64) *GroupMemberDecreaseEvent {
	r.Time = v
	return r
}

// GetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupMemberDecreaseEvent) GetSelfId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.SelfId
}

// SetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupMemberDecreaseEvent) SetSelfId(v int64) *GroupMemberDecreaseEvent {
	r.SelfId = v
	return r
}

// GetPostType
// 上报类型 | 可能的值: notice
func (r *GroupMemberDecreaseEvent) GetPostType() EventPostType {
	if r == nil {
		var zero EventPostType
		return zero
	}
	return r.PostType
}

// SetPostType
// 上报类型 | 可能的值: notice
func (r *GroupMemberDecreaseEvent) SetPostType(v EventPostType) *GroupMemberDecreaseEvent {
	r.PostType = v
	return r
}

// GetNoticeType
// 通知类型 | 可能的值: group_decrease
func (r *GroupMemberDecreaseEvent) GetNoticeType() EventNoticeType {
	if r == nil {
		var zero EventNoticeType
		return zero
	}
	return r.NoticeType
}

// SetNoticeType
// 通知类型 | 可能的值: group_decrease
func (r *GroupMemberDecreaseEvent) SetNoticeType(v EventNoticeType) *GroupMemberDecreaseEvent {
	r.NoticeType = v
	return r
}

// GetSubType
// 事件子类型，分别表示主动退群、成员被踢、登录号被踢 | 可能的值: leave, kick, kick_me
func (r *GroupMemberDecreaseEvent) GetSubType() EventGroupMemberDecreaseSubType {
	if r == nil {
		var zero EventGroupMemberDecreaseSubType
		return zero
	}
	return r.SubType
}

// SetSubType
// 事件子类型，分别表示主动退群、成员被踢、登录号被踢 | 可能的值: leave, kick, kick_me
func (r *GroupMemberDecreaseEvent) SetSubType(v EventGroupMemberDecreaseSubType) *GroupMemberDecreaseEvent {
	r.SubType = v
	return r
}

// GetGroupId
// 群号
func (r *GroupMemberDecreaseEvent) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GroupMemberDecreaseEvent) SetGroupId(v int64) *GroupMemberDecreaseEvent {
	r.GroupId = v
	return r
}

// GetOperatorId
// 操作者 QQ 号（如果是主动退群，则和 `user_id` 相同）
func (r *GroupMemberDecreaseEvent) GetOperatorId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.OperatorId
}

// SetOperatorId
// 操作者 QQ 号（如果是主动退群，则和 `user_id` 相同）
func (r *GroupMemberDecreaseEvent) SetOperatorId(v int64) *GroupMemberDecreaseEvent {
	r.OperatorId = v
	return r
}

// GetUserId
// 离开者 QQ 号
func (r *GroupMemberDecreaseEvent) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 离开者 QQ 号
func (r *GroupMemberDecreaseEvent) SetUserId(v int64) *GroupMemberDecreaseEvent {
	r.UserId = v
	return r
}

// GetTime
// 事件发生的时间戳
func (r *GroupMemberIncreaseEvent) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 事件发生的时间戳
func (r *GroupMemberIncreaseEvent) SetTime(v int64) *GroupMemberIncreaseEvent {
	r.Time = v
	return r
}

// GetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupMemberIncreaseEvent) GetSelfId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.SelfId
}

// SetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupMemberIncreaseEvent) SetSelfId(v int64) *GroupMemberIncreaseEvent {
	r.SelfId = v
	return r
}

// GetPostType
// 上报类型 | 可能的值: notice
func (r *GroupMemberIncreaseEvent) GetPostType() EventPostType {
	if r == nil {
		var zero EventPostType
		return zero
	}
	return r.PostType
}

// SetPostType
// 上报类型 | 可能的值: notice
func (r *GroupMemberIncreaseEvent) SetPostType(v EventPostType) *GroupMemberIncreaseEvent {
	r.PostType = v
	return r
}

// GetNoticeType
// 通知类型 | 可能的值: group_increase
func (r *GroupMemberIncreaseEvent) GetNoticeType() EventNoticeType {
	if r == nil {
		var zero EventNoticeType
		return zero
	}
	return r.NoticeType
}

// SetNoticeType
// 通知类型 | 可能的值: group_increase
func (r *GroupMemberIncreaseEvent) SetNoticeType(v EventNoticeType) *GroupMemberIncreaseEvent {
	r.NoticeType = v
	return r
}

// GetSubType
// 事件子类型，分别表示管理员已同意入群、管理员邀请入群 | 可能的值: approve, invite
func (r *GroupMemberIncreaseEvent) GetSubType() EventGroupMemberIncreaseSubType {
	if r == nil {
		var zero EventGroupMemberIncreaseSubType
		return zero
	}
	return r.SubType
}

// SetSubType
// 事件子类型，分别表示管理员已同意入群、管理员邀请入群 | 可能的值: approve, invite
func (r *GroupMemberIncreaseEvent) SetSubType(v EventGroupMemberIncreaseSubType) *GroupMemberIncreaseEvent {
	r.SubType = v
	return r
}

// GetGroupId
// 群号
func (r *GroupMemberIncreaseEvent) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GroupMemberIncreaseEvent) SetGroupId(v int64) *GroupMemberIncreaseEvent {
	r.GroupId = v
	return r
}

// GetOperatorId
// 操作者 QQ 号
func (r *GroupMemberIncreaseEvent) GetOperatorId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.OperatorId
}

// SetOperatorId
// 操作者 QQ 号
func (r *GroupMemberIncreaseEvent) SetOperatorId(v int64) *GroupMemberIncreaseEvent {
	r.OperatorId = v
	return r
}

// GetUserId
// 加入者 QQ 号
func (r *GroupMemberIncreaseEvent) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 加入者 QQ 号
func (r *GroupMemberIncreaseEvent) SetUserId(v int64) *GroupMemberIncreaseEvent {
	r.UserId = v
	return r
}

// GetTime
// 事件发生的时间戳
func (r *GroupBanEvent) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 事件发生的时间戳
func (r *GroupBanEvent) SetTime(v int64) *GroupBanEvent {
	r.Time = v
	return r
}

// GetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupBanEvent) GetSelfId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.SelfId
}

// SetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupBanEvent) SetSelfId(v int64) *GroupBanEvent {
	r.SelfId = v
	return r
}

// GetPostType
// 上报类型 | 可能的值: notice
func (r *GroupBanEvent) GetPostType() EventPostType {
	if r == nil {
		var zero EventPostType
		return zero
	}
	return r.PostType
}

// SetPostType
// 上报类型 | 可能的值: notice
func (r *GroupBanEvent) SetPostType(v EventPostType) *GroupBanEvent {
	r.PostType = v
	return r
}

// GetNoticeType
// 通知类型 | 可能的值: group_ban
func (r *GroupBanEvent) GetNoticeType() EventNoticeType {
	if r == nil {
		var zero EventNoticeType
		return zero
	}
	return r.NoticeType
}

// SetNoticeType
// 通知类型 | 可能的值: group_ban
func (r *GroupBanEvent) SetNoticeType(v EventNoticeType) *GroupBanEvent {
	r.NoticeType = v
	return r
}

// GetSubType
// 事件子类型，分别表示禁言、解除禁言 | 可能的值: ban, lift_ban
func (r *GroupBanEvent) GetSubType() EventGroupBanSubType {
	if r == nil {
		var zero EventGroupBanSubType
		return zero
	}
	return r.SubType
}

// SetSubType
// 事件子类型，分别表示禁言、解除禁言 | 可能的值: ban, lift_ban
func (r *GroupBanEvent) SetSubType(v EventGroupBanSubType) *GroupBanEvent {
	r.SubType = v
	return r
}

// GetGroupId
// 群号
func (r *GroupBanEvent) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GroupBanEvent) SetGroupId(v int64) *GroupBanEvent {
	r.GroupId = v
	return r
}

// GetOperatorId
// 操作者 QQ 号
func (r *GroupBanEvent) GetOperatorId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.OperatorId
}

// SetOperatorId
// 操作者 QQ 号
func (r *GroupBanEvent) SetOperatorId(v int64) *GroupBanEvent {
	r.OperatorId = v
	return r
}

// GetUserId
// 被禁言 QQ 号
func (r *GroupBanEvent) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 被禁言 QQ 号
func (r *GroupBanEvent) SetUserId(v int64) *GroupBanEvent {
	r.UserId = v
	return r
}

// GetDuration
// 禁言时长，单位秒
func (r *GroupBanEvent) GetDuration() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Duration
}

// SetDuration
// 禁言时长，单位秒
func (r *GroupBanEvent) SetDuration(v int64) *GroupBanEvent {
	r.Duration = v
	return r
}

// GetTime
// 事件发生的时间戳
func (r *FriendAddEvent) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 事件发生的时间戳
func (r *FriendAddEvent) SetTime(v int64) *FriendAddEvent {
	r.Time = v
	return r
}

// GetSelfId
// 收到事件的机器人 QQ 号
func (r *FriendAddEvent) GetSelfId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.SelfId
}

// SetSelfId
// 收到事件的机器人 QQ 号
func (r *FriendAddEvent) SetSelfId(v int64) *FriendAddEvent {
	r.SelfId = v
	return r
}

// GetPostType
// 上报类型 | 可能的值: notice
func (r *FriendAddEvent) GetPostType() EventPostType {
	if r == nil {
		var zero EventPostType
		return zero
	}
	return r.PostType
}

// SetPostType
// 上报类型 | 可能的值: notice
func (r *FriendAddEvent) SetPostType(v EventPostType) *FriendAddEvent {
	r.PostType = v
	return r
}

// GetNoticeType
// 通知类型 | 可能的值: friend_add
func (r *FriendAddEvent) GetNoticeType() EventNoticeType {
	if r == nil {
		var zero EventNoticeType
		return zero
	}
	return r.NoticeType
}

// SetNoticeType
// 通知类型 | 可能的值: friend_add
func (r *FriendAddEvent) SetNoticeType(v EventNoticeType) *FriendAddEvent {
	r.NoticeType = v
	return r
}

// GetUserId
// 新添加好友 QQ 号
func (r *FriendAddEvent) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 新添加好友 QQ 号
func (r *FriendAddEvent) SetUserId(v int64) *FriendAddEvent {
	r.UserId = v
	return r
}

// GetTime
// 事件发生的时间戳
func (r *GroupRecallEvent) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 事件发生的时间戳
func (r *GroupRecallEvent) SetTime(v int64) *GroupRecallEvent {
	r.Time = v
	return r
}

// GetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupRecallEvent) GetSelfId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.SelfId
}

// SetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupRecallEvent) SetSelfId(v int64) *GroupRecallEvent {
	r.SelfId = v
	return r
}

// GetPostType
// 上报类型 | 可能的值: notice
func (r *GroupRecallEvent) GetPostType() EventPostType {
	if r == nil {
		var zero EventPostType
		return zero
	}
	return r.PostType
}

// SetPostType
// 上报类型 | 可能的值: notice
func (r *GroupRecallEvent) SetPostType(v EventPostType) *GroupRecallEvent {
	r.PostType = v
	return r
}

// GetNoticeType
// 通知类型 | 可能的值: group_recall
func (r *GroupRecallEvent) GetNoticeType() EventNoticeType {
	if r == nil {
		var zero EventNoticeType
		return zero
	}
	return r.NoticeType
}

// SetNoticeType
// 通知类型 | 可能的值: group_recall
func (r *GroupRecallEvent) SetNoticeType(v EventNoticeType) *GroupRecallEvent {
	r.NoticeType = v
	return r
}

// GetGroupId
// 群号
func (r *GroupRecallEvent) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GroupRecallEvent) SetGroupId(v int64) *GroupRecallEvent {
	r.GroupId = v
	return r
}

// GetUserId
// 消息发送者 QQ 号
func (r *GroupRecallEvent) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 消息发送者 QQ 号
func (r *GroupRecallEvent) SetUserId(v int64) *GroupRecallEvent {
	r.UserId = v
	return r
}

// GetOperatorId
// 操作者 QQ 号
func (r *GroupRecallEvent) GetOperatorId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.OperatorId
}

// SetOperatorId
// 操作者 QQ 号
func (r *GroupRecallEvent) SetOperatorId(v int64) *GroupRecallEvent {
	r.OperatorId = v
	return r
}

// GetMessageId
// 被撤回的消息 ID
func (r *GroupRecallEvent) GetMessageId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.MessageId
}

// SetMessageId
// 被撤回的消息 ID
func (r *GroupRecallEvent) SetMessageId(v int64) *GroupRecallEvent {
	r.MessageId = v
	return r
}

// GetTime
// 事件发生的时间戳
func (r *FriendRecallEvent) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 事件发生的时间戳
func (r *FriendRecallEvent) SetTime(v int64) *FriendRecallEvent {
	r.Time = v
	return r
}

// GetSelfId
// 收到事件的机器人 QQ 号
func (r *FriendRecallEvent) GetSelfId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.SelfId
}

// SetSelfId
// 收到事件的机器人 QQ 号
func (r *FriendRecallEvent) SetSelfId(v int64) *FriendRecallEvent {
	r.SelfId = v
	return r
}

// GetPostType
// 上报类型 | 可能的值: notice
func (r *FriendRecallEvent) GetPostType() EventPostType {
	if r == nil {
		var zero EventPostType
		return zero
	}
	return r.PostType
}

// SetPostType
// 上报类型 | 可能的值: notice
func (r *FriendRecallEvent) SetPostType(v EventPostType) *FriendRecallEvent {
	r.PostType = v
	return r
}

// GetNoticeType
// 通知类型 | 可能的值: friend_recall
func (r *FriendRecallEvent) GetNoticeType() EventNoticeType {
	if r == nil {
		var zero EventNoticeType
		return zero
	}
	return r.NoticeType
}

// SetNoticeType
// 通知类型 | 可能的值: friend_recall
func (r *FriendRecallEvent) SetNoticeType(v EventNoticeType) *FriendRecallEvent {
	r.NoticeType = v
	return r
}

// GetUserId
// 好友 QQ 号
func (r *FriendRecallEvent) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 好友 QQ 号
func (r *FriendRecallEvent) SetUserId(v int64) *FriendRecallEvent {
	r.UserId = v
	return r
}

// GetMessageId
// 被撤回的消息 ID
func (r *FriendRecallEvent) GetMessageId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.MessageId
}

// SetMessageId
// 被撤回的消息 ID
func (r *FriendRecallEvent) SetMessageId(v int64) *FriendRecallEvent {
	r.MessageId = v
	return r
}

// GetTime
// 事件发生的时间戳
func (r *GroupPokeEvent) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 事件发生的时间戳
func (r *GroupPokeEvent) SetTime(v int64) *GroupPokeEvent {
	r.Time = v
	return r
}

// GetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupPokeEvent) GetSelfId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.SelfId
}

// SetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupPokeEvent) SetSelfId(v int64) *GroupPokeEvent {
	r.SelfId = v
	return r
}

// GetPostType
// 上报类型 | 可能的值: notice
func (r *GroupPokeEvent) GetPostType() EventPostType {
	if r == nil {
		var zero EventPostType
		return zero
	}
	return r.PostType
}

// SetPostType
// 上报类型 | 可能的值: notice
func (r *GroupPokeEvent) SetPostType(v EventPostType) *GroupPokeEvent {
	r.PostType = v
	return r
}

// GetNoticeType
// 消息类型 | 可能的值: notify
func (r *GroupPokeEvent) GetNoticeType() EventNoticeType {
	if r == nil {
		var zero EventNoticeType
		return zero
	}
	return r.NoticeType
}

// SetNoticeType
// 消息类型 | 可能的值: notify
func (r *GroupPokeEvent) SetNoticeType(v EventNoticeType) *GroupPokeEvent {
	r.NoticeType = v
	return r
}

// GetSubType
// 提示类型 | 可能的值: poke
func (r *GroupPokeEvent) GetSubType() EventNoticeSubType {
	if r == nil {
		var zero EventNoticeSubType
		return zero
	}
	return r.SubType
}

// SetSubType
// 提示类型 | 可能的值: poke
func (r *GroupPokeEvent) SetSubType(v EventNoticeSubType) *GroupPokeEvent {
	r.SubType = v
	return r
}

// GetGroupId
// 群号
func (r *GroupPokeEvent) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GroupPokeEvent) SetGroupId(v int64) *GroupPokeEvent {
	r.GroupId = v
	return r
}

// GetUserId
// 发送者 QQ 号
func (r *GroupPokeEvent) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 发送者 QQ 号
func (r *GroupPokeEvent) SetUserId(v int64) *GroupPokeEvent {
	r.UserId = v
	return r
}

// GetTargetId
// 被戳者 QQ 号
func (r *GroupPokeEvent) GetTargetId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.TargetId
}

// SetTargetId
// 被戳者 QQ 号
func (r *GroupPokeEvent) SetTargetId(v int64) *GroupPokeEvent {
	r.TargetId = v
	return r
}

// GetTime
// 事件发生的时间戳
func (r *GroupLuckyKingEvent) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 事件发生的时间戳
func (r *GroupLuckyKingEvent) SetTime(v int64) *GroupLuckyKingEvent {
	r.Time = v
	return r
}

// GetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupLuckyKingEvent) GetSelfId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.SelfId
}

// SetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupLuckyKingEvent) SetSelfId(v int64) *GroupLuckyKingEvent {
	r.SelfId = v
	return r
}

// GetPostType
// 上报类型 | 可能的值: notice
func (r *GroupLuckyKingEvent) GetPostType() EventPostType {
	if r == nil {
		var zero EventPostType
		return zero
	}
	return r.PostType
}

// SetPostType
// 上报类型 | 可能的值: notice
func (r *GroupLuckyKingEvent) SetPostType(v EventPostType) *GroupLuckyKingEvent {
	r.PostType = v
	return r
}

// GetNoticeType
// 消息类型 | 可能的值: notify
func (r *GroupLuckyKingEvent) GetNoticeType() EventNoticeType {
	if r == nil {
		var zero EventNoticeType
		return zero
	}
	return r.NoticeType
}

// SetNoticeType
// 消息类型 | 可能的值: notify
func (r *GroupLuckyKingEvent) SetNoticeType(v EventNoticeType) *GroupLuckyKingEvent {
	r.NoticeType = v
	return r
}

// GetSubType
// 提示类型 | 可能的值: lucky_king
func (r *GroupLuckyKingEvent) GetSubType() EventNoticeSubType {
	if r == nil {
		var zero EventNoticeSubType
		return zero
	}
	return r.SubType
}

// SetSubType
// 提示类型 | 可能的值: lucky_king
func (r *GroupLuckyKingEvent) SetSubType(v EventNoticeSubType) *GroupLuckyKingEvent {
	r.SubType = v
	return r
}

// GetGroupId
// 群号
func (r *GroupLuckyKingEvent) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GroupLuckyKingEvent) SetGroupId(v int64) *GroupLuckyKingEvent {
	r.GroupId = v
	return r
}

// GetUserId
// 红包发送者 QQ 号
func (r *GroupLuckyKingEvent) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 红包发送者 QQ 号
func (r *GroupLuckyKingEvent) SetUserId(v int64) *GroupLuckyKingEvent {
	r.UserId = v
	return r
}

// GetTargetId
// 运气王 QQ 号
func (r *GroupLuckyKingEvent) GetTargetId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.TargetId
}

// SetTargetId
// 运气王 QQ 号
func (r *GroupLuckyKingEvent) SetTargetId(v int64) *GroupLuckyKingEvent {
	r.TargetId = v
	return r
}

// GetTime
// 事件发生的时间戳
func (r *GroupHonorChangeEvent) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 事件发生的时间戳
func (r *GroupHonorChangeEvent) SetTime(v int64) *GroupHonorChangeEvent {
	r.Time = v
	return r
}

// GetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupHonorChangeEvent) GetSelfId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.SelfId
}

// SetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupHonorChangeEvent) SetSelfId(v int64) *GroupHonorChangeEvent {
	r.SelfId = v
	return r
}

// GetPostType
// 上报类型 | 可能的值: notice
func (r *GroupHonorChangeEvent) GetPostType() EventPostType {
	if r == nil {
		var zero EventPostType
		return zero
	}
	return r.PostType
}

// SetPostType
// 上报类型 | 可能的值: notice
func (r *GroupHonorChangeEvent) SetPostType(v EventPostType) *GroupHonorChangeEvent {
	r.PostType = v
	return r
}

// GetNoticeType
// 消息类型 | 可能的值: notify
func (r *GroupHonorChangeEvent) GetNoticeType() EventNoticeType {
	if r == nil {
		var zero EventNoticeType
		return zero
	}
	return r.NoticeType
}

// SetNoticeType
// 消息类型 | 可能的值: notify
func (r *GroupHonorChangeEvent) SetNoticeType(v EventNoticeType) *GroupHonorChangeEvent {
	r.NoticeType = v
	return r
}

// GetSubType
// 提示类型 | 可能的值: honor
func (r *GroupHonorChangeEvent) GetSubType() EventNoticeSubType {
	if r == nil {
		var zero EventNoticeSubType
		return zero
	}
	return r.SubType
}

// SetSubType
// 提示类型 | 可能的值: honor
func (r *GroupHonorChangeEvent) SetSubType(v EventNoticeSubType) *GroupHonorChangeEvent {
	r.SubType = v
	return r
}

// GetGroupId
// 群号
func (r *GroupHonorChangeEvent) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GroupHonorChangeEvent) SetGroupId(v int64) *GroupHonorChangeEvent {
	r.GroupId = v
	return r
}

// GetHonorType
// 荣誉类型，分别表示龙王、群聊之火、快乐源泉 | 可能的值: talkative, performer, emotion
func (r *GroupHonorChangeEvent) GetHonorType() EventGroupHonorChangeHonorType {
	if r == nil {
		var zero EventGroupHonorChangeHonorType
		return zero
	}
	return r.HonorType
}

// SetHonorType
// 荣誉类型，分别表示龙王、群聊之火、快乐源泉 | 可能的值: talkative, performer, emotion
func (r *GroupHonorChangeEvent) SetHonorType(v EventGroupHonorChangeHonorType) *GroupHonorChangeEvent {
	r.HonorType = v
	return r
}

// GetUserId
// 成员 QQ 号
func (r *GroupHonorChangeEvent) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 成员 QQ 号
func (r *GroupHonorChangeEvent) SetUserId(v int64) *GroupHonorChangeEvent {
	r.UserId = v
	return r
}

// GetTime
// 事件发生的时间戳
func (r *FriendRequestEvent) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 事件发生的时间戳
func (r *FriendRequestEvent) SetTime(v int64) *FriendRequestEvent {
	r.Time = v
	return r
}

// GetSelfId
// 收到事件的机器人 QQ 号
func (r *FriendRequestEvent) GetSelfId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.SelfId
}

// SetSelfId
// 收到事件的机器人 QQ 号
func (r *FriendRequestEvent) SetSelfId(v int64) *FriendRequestEvent {
	r.SelfId = v
	return r
}

// GetPostType
// 上报类型 | 可能的值: request
func (r *FriendRequestEvent) GetPostType() EventPostType {
	if r == nil {
		var zero EventPostType
		return zero
	}
	return r.PostType
}

// SetPostType
// 上报类型 | 可能的值: request
func (r *FriendRequestEvent) SetPostType(v EventPostType) *FriendRequestEvent {
	r.PostType = v
	return r
}

// GetRequestType
// 请求类型 | 可能的值: friend
func (r *FriendRequestEvent) GetRequestType() EventRequestType {
	if r == nil {
		var zero EventRequestType
		return zero
	}
	return r.RequestType
}

// SetRequestType
// 请求类型 | 可能的值: friend
func (r *FriendRequestEvent) SetRequestType(v EventRequestType) *FriendRequestEvent {
	r.RequestType = v
	return r
}

// GetUserId
// 发送请求的 QQ 号
func (r *FriendRequestEvent) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 发送请求的 QQ 号
func (r *FriendRequestEvent) SetUserId(v int64) *FriendRequestEvent {
	r.UserId = v
	return r
}

// GetComment
// 验证信息
func (r *FriendRequestEvent) GetComment() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Comment
}

// SetComment
// 验证信息
func (r *FriendRequestEvent) SetComment(v string) *FriendRequestEvent {
	r.Comment = v
	return r
}

// GetFlag
// 请求 flag，在调用处理请求的 API 时需要传入
func (r *FriendRequestEvent) GetFlag() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Flag
}

// SetFlag
// 请求 flag，在调用处理请求的 API 时需要传入
func (r *FriendRequestEvent) SetFlag(v string) *FriendRequestEvent {
	r.Flag = v
	return r
}

// GetTime
// 事件发生的时间戳
func (r *GroupRequestEvent) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 事件发生的时间戳
func (r *GroupRequestEvent) SetTime(v int64) *GroupRequestEvent {
	r.Time = v
	return r
}

// GetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupRequestEvent) GetSelfId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.SelfId
}

// SetSelfId
// 收到事件的机器人 QQ 号
func (r *GroupRequestEvent) SetSelfId(v int64) *GroupRequestEvent {
	r.SelfId = v
	return r
}

// GetPostType
// 上报类型 | 可能的值: request
func (r *GroupRequestEvent) GetPostType() EventPostType {
	if r == nil {
		var zero EventPostType
		return zero
	}
	return r.PostType
}

// SetPostType
// 上报类型 | 可能的值: request
func (r *GroupRequestEvent) SetPostType(v EventPostType) *GroupRequestEvent {
	r.PostType = v
	return r
}

// GetRequestType
// 请求类型 | 可能的值: group
func (r *GroupRequestEvent) GetRequestType() EventRequestType {
	if r == nil {
		var zero EventRequestType
		return zero
	}
	return r.RequestType
}

// SetRequestType
// 请求类型 | 可能的值: group
func (r *GroupRequestEvent) SetRequestType(v EventRequestType) *GroupRequestEvent {
	r.RequestType = v
	return r
}

// GetSubType
// 请求子类型，分别表示加群请求、邀请登录号入群 | 可能的值: add, invite
func (r *GroupRequestEvent) GetSubType() EventGroupRequestSubType {
	if r == nil {
		var zero EventGroupRequestSubType
		return zero
	}
	return r.SubType
}

// SetSubType
// 请求子类型，分别表示加群请求、邀请登录号入群 | 可能的值: add, invite
func (r *GroupRequestEvent) SetSubType(v EventGroupRequestSubType) *GroupRequestEvent {
	r.SubType = v
	return r
}

// GetGroupId
// 群号
func (r *GroupRequestEvent) GetGroupId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.GroupId
}

// SetGroupId
// 群号
func (r *GroupRequestEvent) SetGroupId(v int64) *GroupRequestEvent {
	r.GroupId = v
	return r
}

// GetUserId
// 发送请求的 QQ 号
func (r *GroupRequestEvent) GetUserId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.UserId
}

// SetUserId
// 发送请求的 QQ 号
func (r *GroupRequestEvent) SetUserId(v int64) *GroupRequestEvent {
	r.UserId = v
	return r
}

// GetComment
// 验证信息
func (r *GroupRequestEvent) GetComment() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Comment
}

// SetComment
// 验证信息
func (r *GroupRequestEvent) SetComment(v string) *GroupRequestEvent {
	r.Comment = v
	return r
}

// GetFlag
// 请求 flag，在调用处理请求的 API 时需要传入
func (r *GroupRequestEvent) GetFlag() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Flag
}

// SetFlag
// 请求 flag，在调用处理请求的 API 时需要传入
func (r *GroupRequestEvent) SetFlag(v string) *GroupRequestEvent {
	r.Flag = v
	return r
}

// GetTime
// 事件发生的时间戳
func (r *LifecycleEvent) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 事件发生的时间戳
func (r *LifecycleEvent) SetTime(v int64) *LifecycleEvent {
	r.Time = v
	return r
}

// GetSelfId
// 收到事件的机器人 QQ 号
func (r *LifecycleEvent) GetSelfId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.SelfId
}

// SetSelfId
// 收到事件的机器人 QQ 号
func (r *LifecycleEvent) SetSelfId(v int64) *LifecycleEvent {
	r.SelfId = v
	return r
}

// GetPostType
// 上报类型 | 可能的值: meta_event
func (r *LifecycleEvent) GetPostType() EventPostType {
	if r == nil {
		var zero EventPostType
		return zero
	}
	return r.PostType
}

// SetPostType
// 上报类型 | 可能的值: meta_event
func (r *LifecycleEvent) SetPostType(v EventPostType) *LifecycleEvent {
	r.PostType = v
	return r
}

// GetMetaEventType
// 元事件类型 | 可能的值: lifecycle
func (r *LifecycleEvent) GetMetaEventType() EventMetaType {
	if r == nil {
		var zero EventMetaType
		return zero
	}
	return r.MetaEventType
}

// SetMetaEventType
// 元事件类型 | 可能的值: lifecycle
func (r *LifecycleEvent) SetMetaEventType(v EventMetaType) *LifecycleEvent {
	r.MetaEventType = v
	return r
}

// GetSubType
// 事件子类型，分别表示 OneBot 启用、停用、WebSocket 连接成功 | 可能的值: enable, disable, connect
func (r *LifecycleEvent) GetSubType() EventLifecycleSubType {
	if r == nil {
		var zero EventLifecycleSubType
		return zero
	}
	return r.SubType
}

// SetSubType
// 事件子类型，分别表示 OneBot 启用、停用、WebSocket 连接成功 | 可能的值: enable, disable, connect
func (r *LifecycleEvent) SetSubType(v EventLifecycleSubType) *LifecycleEvent {
	r.SubType = v
	return r
}

// GetTime
// 事件发生的时间戳
func (r *HeartbeatEvent) GetTime() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Time
}

// SetTime
// 事件发生的时间戳
func (r *HeartbeatEvent) SetTime(v int64) *HeartbeatEvent {
	r.Time = v
	return r
}

// GetSelfId
// 收到事件的机器人 QQ 号
func (r *HeartbeatEvent) GetSelfId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.SelfId
}

// SetSelfId
// 收到事件的机器人 QQ 号
func (r *HeartbeatEvent) SetSelfId(v int64) *HeartbeatEvent {
	r.SelfId = v
	return r
}

// GetPostType
// 上报类型 | 可能的值: meta_event
func (r *HeartbeatEvent) GetPostType() EventPostType {
	if r == nil {
		var zero EventPostType
		return zero
	}
	return r.PostType
}

// SetPostType
// 上报类型 | 可能的值: meta_event
func (r *HeartbeatEvent) SetPostType(v EventPostType) *HeartbeatEvent {
	r.PostType = v
	return r
}

// GetMetaEventType
// 元事件类型 | 可能的值: heartbeat
func (r *HeartbeatEvent) GetMetaEventType() EventMetaType {
	if r == nil {
		var zero EventMetaType
		return zero
	}
	return r.MetaEventType
}

// SetMetaEventType
// 元事件类型 | 可能的值: heartbeat
func (r *HeartbeatEvent) SetMetaEventType(v EventMetaType) *HeartbeatEvent {
	r.MetaEventType = v
	return r
}

// GetStatus
// 状态信息
func (r *HeartbeatEvent) GetStatus() *StatusMeta {
	if r == nil {
		var zero *StatusMeta
		return zero
	}
	return r.Status
}

// SetStatus
// 状态信息
func (r *HeartbeatEvent) SetStatus(v *StatusMeta) *HeartbeatEvent {
	r.Status = v
	return r
}

// GetInterval
// 到下次心跳的间隔，单位毫秒
func (r *HeartbeatEvent) GetInterval() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Interval
}

// SetInterval
// 到下次心跳的间隔，单位毫秒
func (r *HeartbeatEvent) SetInterval(v int64) *HeartbeatEvent {
	r.Interval = v
	return r
}
