// Code generated by entity-gen. DO NOT EDIT.

package entity

// GetType
// 如果 Type 为 "string"，则使用 StringValue
// 如果 Type 为 "array"，则使用 ArrayValue
func (r *MessageValue) GetType() MessageValueType {
	if r == nil {
		var zero MessageValueType
		return zero
	}
	return r.Type
}

// SetType
// 如果 Type 为 "string"，则使用 StringValue
// 如果 Type 为 "array"，则使用 ArrayValue
func (r *MessageValue) SetType(v MessageValueType) *MessageValue {
	r.Type = v
	return r
}

func (r *MessageValue) GetStringValue() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.StringValue
}

func (r *MessageValue) SetStringValue(v string) *MessageValue {
	r.StringValue = v
	return r
}

func (r *MessageValue) GetArrayValue() []*Segment {
	if r == nil {
		var zero []*Segment
		return zero
	}
	return r.ArrayValue
}

func (r *MessageValue) SetArrayValue(v []*Segment) *MessageValue {
	r.ArrayValue = v
	return r
}
