// Code generated by entity-gen. DO NOT EDIT.

package entity

func (r *Segment) GetType() SegmentDataType {
	if r == nil {
		var zero SegmentDataType
		return zero
	}
	return r.Type
}

func (r *Segment) SetType(v SegmentDataType) *Segment {
	r.Type = v
	return r
}

func (r *Segment) GetData() SegmentData {
	if r == nil {
		var zero SegmentData
		return zero
	}
	return r.Data
}

func (r *Segment) SetData(v SegmentData) *Segment {
	r.Data = v
	return r
}

// GetText
// 纯文本内容
func (r *TextSegmentData) GetText() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Text
}

// SetText
// 纯文本内容
func (r *TextSegmentData) SetText(v string) *TextSegmentData {
	r.Text = v
	return r
}

// GetId
// QQ 表情 ID | 可能的值: 见 [QQ 表情 ID 表](https://github.com/richardchien/coolq-http-api/wiki/%E8%A1%A8%E6%83%85-CQ-%E7%A0%81-ID-%E8%A1%A8)
func (r *FaceSegmentData) GetId() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Id
}

// SetId
// QQ 表情 ID | 可能的值: 见 [QQ 表情 ID 表](https://github.com/richardchien/coolq-http-api/wiki/%E8%A1%A8%E6%83%85-CQ-%E7%A0%81-ID-%E8%A1%A8)
func (r *FaceSegmentData) SetId(v string) *FaceSegmentData {
	r.Id = v
	return r
}

// GetFile
// 图片文件名
func (r *ImageSegmentData) GetFile() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.File
}

// SetFile
// 图片文件名
func (r *ImageSegmentData) SetFile(v string) *ImageSegmentData {
	r.File = v
	return r
}

// GetType
// 图片类型，`flash` 表示闪照，无此参数表示普通图片 | 可能的值: flash
func (r *ImageSegmentData) GetType() ImageSegmentDataType {
	if r == nil {
		var zero ImageSegmentDataType
		return zero
	}
	return r.Type
}

// SetType
// 图片类型，`flash` 表示闪照，无此参数表示普通图片 | 可能的值: flash
func (r *ImageSegmentData) SetType(v ImageSegmentDataType) *ImageSegmentData {
	r.Type = v
	return r
}

// GetUrl
// 图片 URL
func (r *ImageSegmentData) GetUrl() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Url
}

// SetUrl
// 图片 URL
func (r *ImageSegmentData) SetUrl(v string) *ImageSegmentData {
	r.Url = v
	return r
}

// GetCache
// 只在通过网络 URL 发送时有效，表示是否使用已缓存的文件，默认 `1`
func (r *ImageSegmentData) GetCache() CacheFlag {
	if r == nil {
		var zero CacheFlag
		return zero
	}
	if r.Cache == nil {
		var zero CacheFlag
		return zero
	}
	return *r.Cache
}

// SetCache
// 只在通过网络 URL 发送时有效，表示是否使用已缓存的文件，默认 `1`
func (r *ImageSegmentData) SetCache(v CacheFlag) *ImageSegmentData {
	val := v
	r.Cache = &val
	return r
}

// GetProxy
// 只在通过网络 URL 发送时有效，表示是否通过代理下载文件（需通过环境变量或配置文件配置代理），默认 `1`
func (r *ImageSegmentData) GetProxy() ProxyFlag {
	if r == nil {
		var zero ProxyFlag
		return zero
	}
	if r.Proxy == nil {
		var zero ProxyFlag
		return zero
	}
	return *r.Proxy
}

// SetProxy
// 只在通过网络 URL 发送时有效，表示是否通过代理下载文件（需通过环境变量或配置文件配置代理），默认 `1`
func (r *ImageSegmentData) SetProxy(v ProxyFlag) *ImageSegmentData {
	val := v
	r.Proxy = &val
	return r
}

// GetTimeout
// 只在通过网络 URL 发送时有效，单位秒，表示下载网络文件的超时时间，默认不超时
func (r *ImageSegmentData) GetTimeout() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	if r.Timeout == nil {
		var zero int64
		return zero
	}
	return *r.Timeout
}

// SetTimeout
// 只在通过网络 URL 发送时有效，单位秒，表示下载网络文件的超时时间，默认不超时
func (r *ImageSegmentData) SetTimeout(v int64) *ImageSegmentData {
	val := v
	r.Timeout = &val
	return r
}

// GetFile
// 语音文件名
func (r *RecordSegmentData) GetFile() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.File
}

// SetFile
// 语音文件名
func (r *RecordSegmentData) SetFile(v string) *RecordSegmentData {
	r.File = v
	return r
}

// GetMagic
// 发送时可选，默认 `0`，设置为 `1` 表示变声 | 可能的值: `0` `1`
func (r *RecordSegmentData) GetMagic() MagicFlag {
	if r == nil {
		var zero MagicFlag
		return zero
	}
	if r.Magic == nil {
		var zero MagicFlag
		return zero
	}
	return *r.Magic
}

// SetMagic
// 发送时可选，默认 `0`，设置为 `1` 表示变声 | 可能的值: `0` `1`
func (r *RecordSegmentData) SetMagic(v MagicFlag) *RecordSegmentData {
	val := v
	r.Magic = &val
	return r
}

// GetUrl
// 语音 URL
func (r *RecordSegmentData) GetUrl() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Url
}

// SetUrl
// 语音 URL
func (r *RecordSegmentData) SetUrl(v string) *RecordSegmentData {
	r.Url = v
	return r
}

// GetCache
// 只在通过网络 URL 发送时有效，表示是否使用已缓存的文件，默认 `1`
func (r *RecordSegmentData) GetCache() CacheFlag {
	if r == nil {
		var zero CacheFlag
		return zero
	}
	if r.Cache == nil {
		var zero CacheFlag
		return zero
	}
	return *r.Cache
}

// SetCache
// 只在通过网络 URL 发送时有效，表示是否使用已缓存的文件，默认 `1`
func (r *RecordSegmentData) SetCache(v CacheFlag) *RecordSegmentData {
	val := v
	r.Cache = &val
	return r
}

// GetProxy
// 只在通过网络 URL 发送时有效，表示是否通过代理下载文件（需通过环境变量或配置文件配置代理），默认 `1`
func (r *RecordSegmentData) GetProxy() ProxyFlag {
	if r == nil {
		var zero ProxyFlag
		return zero
	}
	if r.Proxy == nil {
		var zero ProxyFlag
		return zero
	}
	return *r.Proxy
}

// SetProxy
// 只在通过网络 URL 发送时有效，表示是否通过代理下载文件（需通过环境变量或配置文件配置代理），默认 `1`
func (r *RecordSegmentData) SetProxy(v ProxyFlag) *RecordSegmentData {
	val := v
	r.Proxy = &val
	return r
}

// GetTimeout
// 只在通过网络 URL 发送时有效，单位秒，表示下载网络文件的超时时间 ，默认不超时
func (r *RecordSegmentData) GetTimeout() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	if r.Timeout == nil {
		var zero int64
		return zero
	}
	return *r.Timeout
}

// SetTimeout
// 只在通过网络 URL 发送时有效，单位秒，表示下载网络文件的超时时间 ，默认不超时
func (r *RecordSegmentData) SetTimeout(v int64) *RecordSegmentData {
	val := v
	r.Timeout = &val
	return r
}

// GetFile
// 视频文件名
func (r *VideoSegmentData) GetFile() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.File
}

// SetFile
// 视频文件名
func (r *VideoSegmentData) SetFile(v string) *VideoSegmentData {
	r.File = v
	return r
}

// GetUrl
// 视频 URL
func (r *VideoSegmentData) GetUrl() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Url
}

// SetUrl
// 视频 URL
func (r *VideoSegmentData) SetUrl(v string) *VideoSegmentData {
	r.Url = v
	return r
}

// GetCache
// 只在通过网络 URL 发送时有效，表示是否使用已缓存的文件，默认 `1`
func (r *VideoSegmentData) GetCache() CacheFlag {
	if r == nil {
		var zero CacheFlag
		return zero
	}
	if r.Cache == nil {
		var zero CacheFlag
		return zero
	}
	return *r.Cache
}

// SetCache
// 只在通过网络 URL 发送时有效，表示是否使用已缓存的文件，默认 `1`
func (r *VideoSegmentData) SetCache(v CacheFlag) *VideoSegmentData {
	val := v
	r.Cache = &val
	return r
}

// GetProxy
// 只在通过网络 URL 发送时有效，表示是否通过代理下载文件（需通过环境变量或配置文件配置代理），默认 `1`
func (r *VideoSegmentData) GetProxy() ProxyFlag {
	if r == nil {
		var zero ProxyFlag
		return zero
	}
	if r.Proxy == nil {
		var zero ProxyFlag
		return zero
	}
	return *r.Proxy
}

// SetProxy
// 只在通过网络 URL 发送时有效，表示是否通过代理下载文件（需通过环境变量或配置文件配置代理），默认 `1`
func (r *VideoSegmentData) SetProxy(v ProxyFlag) *VideoSegmentData {
	val := v
	r.Proxy = &val
	return r
}

// GetTimeout
// 只在通过网络 URL 发送时有效，单位秒，表示下载网络文件的超时时间 ，默认不超时
func (r *VideoSegmentData) GetTimeout() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	if r.Timeout == nil {
		var zero int64
		return zero
	}
	return *r.Timeout
}

// SetTimeout
// 只在通过网络 URL 发送时有效，单位秒，表示下载网络文件的超时时间 ，默认不超时
func (r *VideoSegmentData) SetTimeout(v int64) *VideoSegmentData {
	val := v
	r.Timeout = &val
	return r
}

// GetQQ
// @的 QQ 号，`all` 表示全体成员 | 可能的值: QQ 号, all
func (r *AtSegmentData) GetQQ() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.QQ
}

// SetQQ
// @的 QQ 号，`all` 表示全体成员 | 可能的值: QQ 号, all
func (r *AtSegmentData) SetQQ(v string) *AtSegmentData {
	r.QQ = v
	return r
}

// GetType
// 类型 | 可能的值: 见 segment_consts.go 中的 PokeSegmentData enums.
func (r *PokeSegmentData) GetType() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Type
}

// SetType
// 类型 | 可能的值: 见 segment_consts.go 中的 PokeSegmentData enums.
func (r *PokeSegmentData) SetType(v string) *PokeSegmentData {
	r.Type = v
	return r
}

// GetId
// ID | 可能的值: 同上
func (r *PokeSegmentData) GetId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Id
}

// SetId
// ID | 可能的值: 同上
func (r *PokeSegmentData) SetId(v int64) *PokeSegmentData {
	r.Id = v
	return r
}

// GetName
// 表情名
func (r *PokeSegmentData) GetName() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.Name
}

// SetName
// 表情名
func (r *PokeSegmentData) SetName(v int64) *PokeSegmentData {
	r.Name = v
	return r
}

// GetIgnore
// 可选，表示无法匿名时是否继续发送 | 可能的值: `0`, `1`
func (r *AnonymousSegmentData) GetIgnore() IgnoreFlag {
	if r == nil {
		var zero IgnoreFlag
		return zero
	}
	if r.Ignore == nil {
		var zero IgnoreFlag
		return zero
	}
	return *r.Ignore
}

// SetIgnore
// 可选，表示无法匿名时是否继续发送 | 可能的值: `0`, `1`
func (r *AnonymousSegmentData) SetIgnore(v IgnoreFlag) *AnonymousSegmentData {
	val := v
	r.Ignore = &val
	return r
}

// GetUrl
// URL
func (r *ShareSegmentData) GetUrl() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Url
}

// SetUrl
// URL
func (r *ShareSegmentData) SetUrl(v string) *ShareSegmentData {
	r.Url = v
	return r
}

// GetTitle
// 标题
func (r *ShareSegmentData) GetTitle() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Title
}

// SetTitle
// 标题
func (r *ShareSegmentData) SetTitle(v string) *ShareSegmentData {
	r.Title = v
	return r
}

// GetContent
// 发送时可选，内容描述
func (r *ShareSegmentData) GetContent() string {
	if r == nil {
		var zero string
		return zero
	}
	if r.Content == nil {
		var zero string
		return zero
	}
	return *r.Content
}

// SetContent
// 发送时可选，内容描述
func (r *ShareSegmentData) SetContent(v string) *ShareSegmentData {
	val := v
	r.Content = &val
	return r
}

// GetImage
// 发送时可选，图片 URL
func (r *ShareSegmentData) GetImage() string {
	if r == nil {
		var zero string
		return zero
	}
	if r.Image == nil {
		var zero string
		return zero
	}
	return *r.Image
}

// SetImage
// 发送时可选，图片 URL
func (r *ShareSegmentData) SetImage(v string) *ShareSegmentData {
	val := v
	r.Image = &val
	return r
}

// GetType
// 推荐好友 | 可能的值: qq, group
func (r *ContactSegmentData) GetType() ContactSegmentDataType {
	if r == nil {
		var zero ContactSegmentDataType
		return zero
	}
	return r.Type
}

// SetType
// 推荐好友 | 可能的值: qq, group
func (r *ContactSegmentData) SetType(v ContactSegmentDataType) *ContactSegmentData {
	r.Type = v
	return r
}

// GetId
// 被推荐人的 QQ 号/群号
func (r *ContactSegmentData) GetId() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Id
}

// SetId
// 被推荐人的 QQ 号/群号
func (r *ContactSegmentData) SetId(v string) *ContactSegmentData {
	r.Id = v
	return r
}

// GetLat
// 纬度
func (r *LocationSegmentData) GetLat() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Lat
}

// SetLat
// 纬度
func (r *LocationSegmentData) SetLat(v string) *LocationSegmentData {
	r.Lat = v
	return r
}

// GetLon
// 经度
func (r *LocationSegmentData) GetLon() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Lon
}

// SetLon
// 经度
func (r *LocationSegmentData) SetLon(v string) *LocationSegmentData {
	r.Lon = v
	return r
}

// GetTitle
// 发送时可选，标题
func (r *LocationSegmentData) GetTitle() string {
	if r == nil {
		var zero string
		return zero
	}
	if r.Title == nil {
		var zero string
		return zero
	}
	return *r.Title
}

// SetTitle
// 发送时可选，标题
func (r *LocationSegmentData) SetTitle(v string) *LocationSegmentData {
	val := v
	r.Title = &val
	return r
}

// GetContent
// 发送时可选，内容描述
func (r *LocationSegmentData) GetContent() string {
	if r == nil {
		var zero string
		return zero
	}
	if r.Content == nil {
		var zero string
		return zero
	}
	return *r.Content
}

// SetContent
// 发送时可选，内容描述
func (r *LocationSegmentData) SetContent(v string) *LocationSegmentData {
	val := v
	r.Content = &val
	return r
}

// GetType
// 表示使用 QQ 音乐、网易云音乐、虾米音乐或音乐自定义分享 | 可能的值: qq, 163, xm, custom
func (r *MusicSegmentData) GetType() MusicType {
	if r == nil {
		var zero MusicType
		return zero
	}
	return r.Type
}

// SetType
// 表示使用 QQ 音乐、网易云音乐、虾米音乐或音乐自定义分享 | 可能的值: qq, 163, xm, custom
func (r *MusicSegmentData) SetType(v MusicType) *MusicSegmentData {
	r.Type = v
	return r
}

// GetId
// 歌曲 ID (使用 QQ 音乐、网易云音乐、虾米音乐)
func (r *MusicSegmentData) GetId() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Id
}

// SetId
// 歌曲 ID (使用 QQ 音乐、网易云音乐、虾米音乐)
func (r *MusicSegmentData) SetId(v string) *MusicSegmentData {
	r.Id = v
	return r
}

// GetUrl
// 音乐自定义分享
// 点击后跳转目标 URL
func (r *MusicSegmentData) GetUrl() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Url
}

// SetUrl
// 音乐自定义分享
// 点击后跳转目标 URL
func (r *MusicSegmentData) SetUrl(v string) *MusicSegmentData {
	r.Url = v
	return r
}

// GetAudio
// 音乐 URL
func (r *MusicSegmentData) GetAudio() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Audio
}

// SetAudio
// 音乐 URL
func (r *MusicSegmentData) SetAudio(v string) *MusicSegmentData {
	r.Audio = v
	return r
}

// GetTitle
// 标题
func (r *MusicSegmentData) GetTitle() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Title
}

// SetTitle
// 标题
func (r *MusicSegmentData) SetTitle(v string) *MusicSegmentData {
	r.Title = v
	return r
}

// GetContent
// 发送时可选，内容描述
func (r *MusicSegmentData) GetContent() string {
	if r == nil {
		var zero string
		return zero
	}
	if r.Content == nil {
		var zero string
		return zero
	}
	return *r.Content
}

// SetContent
// 发送时可选，内容描述
func (r *MusicSegmentData) SetContent(v string) *MusicSegmentData {
	val := v
	r.Content = &val
	return r
}

// GetImage
// 发送时可选，图片 URL
func (r *MusicSegmentData) GetImage() string {
	if r == nil {
		var zero string
		return zero
	}
	if r.Image == nil {
		var zero string
		return zero
	}
	return *r.Image
}

// SetImage
// 发送时可选，图片 URL
func (r *MusicSegmentData) SetImage(v string) *MusicSegmentData {
	val := v
	r.Image = &val
	return r
}

// GetId
// 回复时引用的消息 ID
func (r *ReplySegmentData) GetId() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Id
}

// SetId
// 回复时引用的消息 ID
func (r *ReplySegmentData) SetId(v string) *ReplySegmentData {
	r.Id = v
	return r
}

// GetId
// 合并转发 ID，需通过 get_forward_msg-获取合并转发消息 获取具体内容
func (r *ForwardSegmentData) GetId() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Id
}

// SetId
// 合并转发 ID，需通过 get_forward_msg-获取合并转发消息 获取具体内容
func (r *ForwardSegmentData) SetId(v string) *ForwardSegmentData {
	r.Id = v
	return r
}

// GetId
// 转发的消息 ID
func (r *NodeSegmentData) GetId() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Id
}

// SetId
// 转发的消息 ID
func (r *NodeSegmentData) SetId(v string) *NodeSegmentData {
	r.Id = v
	return r
}

// GetUserId
// 发送者 QQ 号
func (r *NodeSegmentData) GetUserId() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.UserId
}

// SetUserId
// 发送者 QQ 号
func (r *NodeSegmentData) SetUserId(v string) *NodeSegmentData {
	r.UserId = v
	return r
}

// GetNickname
// 发送者昵称
func (r *NodeSegmentData) GetNickname() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Nickname
}

// SetNickname
// 发送者昵称
func (r *NodeSegmentData) SetNickname(v string) *NodeSegmentData {
	r.Nickname = v
	return r
}

// GetContent
// 消息内容，支持发送消息时的 `message` 数据类型
func (r *NodeSegmentData) GetContent() *MessageValue {
	if r == nil {
		var zero *MessageValue
		return zero
	}
	return r.Content
}

// SetContent
// 消息内容，支持发送消息时的 `message` 数据类型
func (r *NodeSegmentData) SetContent(v *MessageValue) *NodeSegmentData {
	r.Content = v
	return r
}

// GetData
// XML 内容
func (r *XmlSegmentData) GetData() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Data
}

// SetData
// XML 内容
func (r *XmlSegmentData) SetData(v string) *XmlSegmentData {
	r.Data = v
	return r
}

// GetData
// JSON 内容
func (r *JsonSegmentData) GetData() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.Data
}

// SetData
// JSON 内容
func (r *JsonSegmentData) SetData(v string) *JsonSegmentData {
	r.Data = v
	return r
}
