// Code generated by bindings-gen. DO NOT EDIT.
// Source: cmd/bindings-gen/config.yaml

package client

import (
	"context"
	"encoding/json"

	"github.com/q1bksuu/onebot-go-sdk/v11/entity"
)

// SendPrivateMsg calls action "send_private_msg".
func (c *HTTPClient) SendPrivateMsg(
	ctx context.Context,
	req *entity.SendPrivateMsgRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.SendPrivateMsgResponse], error) {
	rawResponse, err := c.do(ctx, "send_private_msg", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.SendPrivateMsgResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SendGroupMsg calls action "send_group_msg".
func (c *HTTPClient) SendGroupMsg(
	ctx context.Context,
	req *entity.SendGroupMsgRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.SendGroupMsgResponse], error) {
	rawResponse, err := c.do(ctx, "send_group_msg", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.SendGroupMsgResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SendMsg calls action "send_msg".
func (c *HTTPClient) SendMsg(
	ctx context.Context,
	req *entity.SendMsgRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.SendMsgResponse], error) {
	rawResponse, err := c.do(ctx, "send_msg", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.SendMsgResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteMsg calls action "delete_msg".
func (c *HTTPClient) DeleteMsg(
	ctx context.Context,
	req *entity.DeleteMsgRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.DeleteMsgResponse], error) {
	rawResponse, err := c.do(ctx, "delete_msg", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.DeleteMsgResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMsg calls action "get_msg".
func (c *HTTPClient) GetMsg(
	ctx context.Context,
	req *entity.GetMsgRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.GetMsgResponse], error) {
	rawResponse, err := c.do(ctx, "get_msg", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.GetMsgResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetForwardMsg calls action "get_forward_msg".
func (c *HTTPClient) GetForwardMsg(
	ctx context.Context,
	req *entity.GetForwardMsgRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.GetForwardMsgResponse], error) {
	rawResponse, err := c.do(ctx, "get_forward_msg", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.GetForwardMsgResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SendLike calls action "send_like".
func (c *HTTPClient) SendLike(
	ctx context.Context,
	req *entity.SendLikeRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.SendLikeResponse], error) {
	rawResponse, err := c.do(ctx, "send_like", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.SendLikeResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetFriendAddRequest calls action "set_friend_add_request".
func (c *HTTPClient) SetFriendAddRequest(
	ctx context.Context,
	req *entity.SetFriendAddRequestRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.SetFriendAddRequestResponse], error) {
	rawResponse, err := c.do(ctx, "set_friend_add_request", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.SetFriendAddRequestResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetStrangerInfo calls action "get_stranger_info".
func (c *HTTPClient) GetStrangerInfo(
	ctx context.Context,
	req *entity.GetStrangerInfoRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.GetStrangerInfoResponse], error) {
	rawResponse, err := c.do(ctx, "get_stranger_info", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.GetStrangerInfoResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetFriendList calls action "get_friend_list".
func (c *HTTPClient) GetFriendList(
	ctx context.Context,
	req *entity.GetFriendListRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.GetFriendListResponse], error) {
	rawResponse, err := c.do(ctx, "get_friend_list", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.GetFriendListResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetGroupKick calls action "set_group_kick".
func (c *HTTPClient) SetGroupKick(
	ctx context.Context,
	req *entity.SetGroupKickRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.SetGroupKickResponse], error) {
	rawResponse, err := c.do(ctx, "set_group_kick", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.SetGroupKickResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetGroupBan calls action "set_group_ban".
func (c *HTTPClient) SetGroupBan(
	ctx context.Context,
	req *entity.SetGroupBanRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.SetGroupBanResponse], error) {
	rawResponse, err := c.do(ctx, "set_group_ban", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.SetGroupBanResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetGroupAnonymousBan calls action "set_group_anonymous_ban".
func (c *HTTPClient) SetGroupAnonymousBan(
	ctx context.Context,
	req *entity.SetGroupAnonymousBanRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.SetGroupAnonymousBanResponse], error) {
	rawResponse, err := c.do(ctx, "set_group_anonymous_ban", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.SetGroupAnonymousBanResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetGroupWholeBan calls action "set_group_whole_ban".
func (c *HTTPClient) SetGroupWholeBan(
	ctx context.Context,
	req *entity.SetGroupWholeBanRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.SetGroupWholeBanResponse], error) {
	rawResponse, err := c.do(ctx, "set_group_whole_ban", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.SetGroupWholeBanResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetGroupAdmin calls action "set_group_admin".
func (c *HTTPClient) SetGroupAdmin(
	ctx context.Context,
	req *entity.SetGroupAdminRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.SetGroupAdminResponse], error) {
	rawResponse, err := c.do(ctx, "set_group_admin", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.SetGroupAdminResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetGroupAnonymous calls action "set_group_anonymous".
func (c *HTTPClient) SetGroupAnonymous(
	ctx context.Context,
	req *entity.SetGroupAnonymousRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.SetGroupAnonymousResponse], error) {
	rawResponse, err := c.do(ctx, "set_group_anonymous", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.SetGroupAnonymousResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetGroupCard calls action "set_group_card".
func (c *HTTPClient) SetGroupCard(
	ctx context.Context,
	req *entity.SetGroupCardRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.SetGroupCardResponse], error) {
	rawResponse, err := c.do(ctx, "set_group_card", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.SetGroupCardResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetGroupName calls action "set_group_name".
func (c *HTTPClient) SetGroupName(
	ctx context.Context,
	req *entity.SetGroupNameRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.SetGroupNameResponse], error) {
	rawResponse, err := c.do(ctx, "set_group_name", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.SetGroupNameResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetGroupLeave calls action "set_group_leave".
func (c *HTTPClient) SetGroupLeave(
	ctx context.Context,
	req *entity.SetGroupLeaveRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.SetGroupLeaveResponse], error) {
	rawResponse, err := c.do(ctx, "set_group_leave", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.SetGroupLeaveResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetGroupSpecialTitle calls action "set_group_special_title".
func (c *HTTPClient) SetGroupSpecialTitle(
	ctx context.Context,
	req *entity.SetGroupSpecialTitleRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.SetGroupSpecialTitleResponse], error) {
	rawResponse, err := c.do(ctx, "set_group_special_title", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.SetGroupSpecialTitleResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetGroupAddRequest calls action "set_group_add_request".
func (c *HTTPClient) SetGroupAddRequest(
	ctx context.Context,
	req *entity.SetGroupAddRequestRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.SetGroupAddRequestResponse], error) {
	rawResponse, err := c.do(ctx, "set_group_add_request", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.SetGroupAddRequestResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetGroupInfo calls action "get_group_info".
func (c *HTTPClient) GetGroupInfo(
	ctx context.Context,
	req *entity.GetGroupInfoRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.GetGroupInfoResponse], error) {
	rawResponse, err := c.do(ctx, "get_group_info", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.GetGroupInfoResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetGroupList calls action "get_group_list".
func (c *HTTPClient) GetGroupList(
	ctx context.Context,
	req *entity.GetGroupListRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.GetGroupListResponse], error) {
	rawResponse, err := c.do(ctx, "get_group_list", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.GetGroupListResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetGroupMemberInfo calls action "get_group_member_info".
func (c *HTTPClient) GetGroupMemberInfo(
	ctx context.Context,
	req *entity.GetGroupMemberInfoRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.GetGroupMemberInfoResponse], error) {
	rawResponse, err := c.do(ctx, "get_group_member_info", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.GetGroupMemberInfoResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetGroupMemberList calls action "get_group_member_list".
func (c *HTTPClient) GetGroupMemberList(
	ctx context.Context,
	req *entity.GetGroupMemberListRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.GetGroupMemberListResponse], error) {
	rawResponse, err := c.do(ctx, "get_group_member_list", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.GetGroupMemberListResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetGroupHonorInfo calls action "get_group_honor_info".
func (c *HTTPClient) GetGroupHonorInfo(
	ctx context.Context,
	req *entity.GetGroupHonorInfoRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.GetGroupHonorInfoResponse], error) {
	rawResponse, err := c.do(ctx, "get_group_honor_info", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.GetGroupHonorInfoResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetLoginInfo calls action "get_login_info".
func (c *HTTPClient) GetLoginInfo(
	ctx context.Context,
	req *entity.GetLoginInfoRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.GetLoginInfoResponse], error) {
	rawResponse, err := c.do(ctx, "get_login_info", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.GetLoginInfoResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCookies calls action "get_cookies".
func (c *HTTPClient) GetCookies(
	ctx context.Context,
	req *entity.GetCookiesRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.GetCookiesResponse], error) {
	rawResponse, err := c.do(ctx, "get_cookies", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.GetCookiesResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCsrfToken calls action "get_csrf_token".
func (c *HTTPClient) GetCsrfToken(
	ctx context.Context,
	req *entity.GetCsrfTokenRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.GetCsrfTokenResponse], error) {
	rawResponse, err := c.do(ctx, "get_csrf_token", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.GetCsrfTokenResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCredentials calls action "get_credentials".
func (c *HTTPClient) GetCredentials(
	ctx context.Context,
	req *entity.GetCredentialsRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.GetCredentialsResponse], error) {
	rawResponse, err := c.do(ctx, "get_credentials", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.GetCredentialsResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRecord calls action "get_record".
func (c *HTTPClient) GetRecord(
	ctx context.Context,
	req *entity.GetRecordRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.GetRecordResponse], error) {
	rawResponse, err := c.do(ctx, "get_record", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.GetRecordResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetImage calls action "get_image".
func (c *HTTPClient) GetImage(
	ctx context.Context,
	req *entity.GetImageRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.GetImageResponse], error) {
	rawResponse, err := c.do(ctx, "get_image", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.GetImageResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CanSendImage calls action "can_send_image".
func (c *HTTPClient) CanSendImage(
	ctx context.Context,
	req *entity.CanSendImageRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.CanSendImageResponse], error) {
	rawResponse, err := c.do(ctx, "can_send_image", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.CanSendImageResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CanSendRecord calls action "can_send_record".
func (c *HTTPClient) CanSendRecord(
	ctx context.Context,
	req *entity.CanSendRecordRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.CanSendRecordResponse], error) {
	rawResponse, err := c.do(ctx, "can_send_record", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.CanSendRecordResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetStatus calls action "get_status".
func (c *HTTPClient) GetStatus(
	ctx context.Context,
	req *entity.GetStatusRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.GetStatusResponse], error) {
	rawResponse, err := c.do(ctx, "get_status", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.GetStatusResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetVersionInfo calls action "get_version_info".
func (c *HTTPClient) GetVersionInfo(
	ctx context.Context,
	req *entity.GetVersionInfoRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.GetVersionInfoResponse], error) {
	rawResponse, err := c.do(ctx, "get_version_info", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.GetVersionInfoResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetRestart calls action "set_restart".
func (c *HTTPClient) SetRestart(
	ctx context.Context,
	req *entity.SetRestartRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.SetRestartResponse], error) {
	rawResponse, err := c.do(ctx, "set_restart", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.SetRestartResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CleanCache calls action "clean_cache".
func (c *HTTPClient) CleanCache(
	ctx context.Context,
	req *entity.CleanCacheRequest,
	opts ...CallOption,
) (*entity.ActionResponse[entity.CleanCacheResponse], error) {
	rawResponse, err := c.do(ctx, "clean_cache", "POST", req, opts...)
	if err != nil {
		return nil, err
	}

	out := entity.ActionResponse[entity.CleanCacheResponse]{
		Status:  rawResponse.Status,
		Retcode: rawResponse.Retcode,
		Message: rawResponse.Message,
	}
	err = json.Unmarshal(rawResponse.GetData(), &out.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
